-- Phase 5 storage policies for ziko- buckets (D-03). Generated by 07-generate-storage-policies.mjs from live ziko metadata.
-- generated file: do not edit by hand
-- expected policy count: 25

BEGIN;

DROP POLICY IF EXISTS "ziko_ai_imports_owner_delete" ON storage.objects;
CREATE POLICY "ziko_ai_imports_owner_delete" ON storage.objects AS PERMISSIVE FOR DELETE TO public
  USING (((bucket_id = 'ziko-ai-imports'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));

DROP POLICY IF EXISTS "ziko_ai_imports_owner_insert" ON storage.objects;
CREATE POLICY "ziko_ai_imports_owner_insert" ON storage.objects AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((bucket_id = 'ziko-ai-imports'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));

DROP POLICY IF EXISTS "ziko_ai_imports_owner_select" ON storage.objects;
CREATE POLICY "ziko_ai_imports_owner_select" ON storage.objects AS PERMISSIVE FOR SELECT TO public
  USING (((bucket_id = 'ziko-ai-imports'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));

DROP POLICY IF EXISTS "ziko_avatar_delete" ON storage.objects;
CREATE POLICY "ziko_avatar_delete" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated
  USING (((bucket_id = 'ziko-avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_avatar_public_read" ON storage.objects;
CREATE POLICY "ziko_avatar_public_read" ON storage.objects AS PERMISSIVE FOR SELECT TO public
  USING ((bucket_id = 'ziko-avatars'::text));

DROP POLICY IF EXISTS "ziko_avatar_update" ON storage.objects;
CREATE POLICY "ziko_avatar_update" ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((bucket_id = 'ziko-avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)))
  WITH CHECK (((bucket_id = 'ziko-avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_avatar_upload" ON storage.objects;
CREATE POLICY "ziko_avatar_upload" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((bucket_id = 'ziko-avatars'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_coach_exercises_delete" ON storage.objects;
CREATE POLICY "ziko_coach_exercises_delete" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated
  USING (((bucket_id = 'ziko-coach-exercises'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_coach_exercises_insert" ON storage.objects;
CREATE POLICY "ziko_coach_exercises_insert" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((bucket_id = 'ziko-coach-exercises'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_coach_exercises_select" ON storage.objects;
CREATE POLICY "ziko_coach_exercises_select" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated
  USING (((bucket_id = 'ziko-coach-exercises'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_coach_kyc_delete" ON storage.objects;
CREATE POLICY "ziko_coach_kyc_delete" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated
  USING (((bucket_id = 'ziko-coach-kyc'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_coach_kyc_insert" ON storage.objects;
CREATE POLICY "ziko_coach_kyc_insert" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((bucket_id = 'ziko-coach-kyc'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_coach_kyc_select" ON storage.objects;
CREATE POLICY "ziko_coach_kyc_select" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated
  USING (((bucket_id = 'ziko-coach-kyc'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_coach_logos_coach_write" ON storage.objects;
CREATE POLICY "ziko_coach_logos_coach_write" ON storage.objects AS PERMISSIVE FOR ALL TO authenticated
  USING (((bucket_id = 'ziko-coach-logos'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)))
  WITH CHECK (((bucket_id = 'ziko-coach-logos'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_coach_logos_public_read" ON storage.objects;
CREATE POLICY "ziko_coach_logos_public_read" ON storage.objects AS PERMISSIVE FOR SELECT TO public
  USING ((bucket_id = 'ziko-coach-logos'::text));

DROP POLICY IF EXISTS "ziko_coach_videos_athlete_read" ON storage.objects;
CREATE POLICY "ziko_coach_videos_athlete_read" ON storage.objects AS PERMISSIVE FOR SELECT TO public
  USING (((bucket_id = 'ziko-coach-videos'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));

DROP POLICY IF EXISTS "ziko_coach_videos_athlete_upload" ON storage.objects;
CREATE POLICY "ziko_coach_videos_athlete_upload" ON storage.objects AS PERMISSIVE FOR INSERT TO public
  WITH CHECK (((bucket_id = 'ziko-coach-videos'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));

DROP POLICY IF EXISTS "ziko_coach_videos_coach_read" ON storage.objects;
CREATE POLICY "ziko_coach_videos_coach_read" ON storage.objects AS PERMISSIVE FOR SELECT TO public
  USING (((bucket_id = 'ziko-coach-videos'::text) AND public.ziko_is_coach_of(auth.uid(), ((storage.foldername(name))[1])::uuid)));

DROP POLICY IF EXISTS "ziko_exports_read" ON storage.objects;
CREATE POLICY "ziko_exports_read" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated
  USING (((bucket_id = 'ziko-exports'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_profile_photos_insert" ON storage.objects;
CREATE POLICY "ziko_profile_photos_insert" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((bucket_id = 'ziko-profile-photos'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_profile_photos_public_read" ON storage.objects;
CREATE POLICY "ziko_profile_photos_public_read" ON storage.objects AS PERMISSIVE FOR SELECT TO public
  USING ((bucket_id = 'ziko-profile-photos'::text));

DROP POLICY IF EXISTS "ziko_profile_photos_update" ON storage.objects;
CREATE POLICY "ziko_profile_photos_update" ON storage.objects AS PERMISSIVE FOR UPDATE TO authenticated
  USING (((bucket_id = 'ziko-profile-photos'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_scan_photos_delete" ON storage.objects;
CREATE POLICY "ziko_scan_photos_delete" ON storage.objects AS PERMISSIVE FOR DELETE TO authenticated
  USING (((bucket_id = 'ziko-scan-photos'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_scan_photos_read" ON storage.objects;
CREATE POLICY "ziko_scan_photos_read" ON storage.objects AS PERMISSIVE FOR SELECT TO authenticated
  USING (((bucket_id = 'ziko-scan-photos'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

DROP POLICY IF EXISTS "ziko_scan_photos_upload" ON storage.objects;
CREATE POLICY "ziko_scan_photos_upload" ON storage.objects AS PERMISSIVE FOR INSERT TO authenticated
  WITH CHECK (((bucket_id = 'ziko-scan-photos'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

COMMIT;
