// Generated by scripts/portfolio-migration/11-codemod-buckets.mjs from bucket-map.generated.json.
// Do not edit by hand.
export const STORAGE_BUCKETS = {
  aiImports: 'ziko-ai-imports',
  avatars: 'ziko-avatars',
  coachExercises: 'ziko-coach-exercises',
  coachKyc: 'ziko-coach-kyc',
  coachLogos: 'ziko-coach-logos',
  coachVideos: 'ziko-coach-videos',
  exerciseMedia: 'ziko-exercise-media',
  exports: 'ziko-exports',
  profilePhotos: 'ziko-profile-photos',
  scanPhotos: 'ziko-scan-photos',
} as const;

export type StorageBucket = (typeof STORAGE_BUCKETS)[keyof typeof STORAGE_BUCKETS];
