export interface RecipeIngredient {
  name: string;
  quantity: number;
  unit: string;
}

export interface RecipeMacros {
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
}

export interface Recipe {
  id: string;           // short slug generated by AI, used as React key
  name: string;
  description: string;
  prep_time_min: number;
  base_servings: number; // default serving count (1 or 2)
  ingredients: RecipeIngredient[];
  macros: RecipeMacros;  // values are for base_servings portions
  steps: string[];
}

export interface MacroBudget {
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
}
