import json, sys
sys.stdout.reconfigure(encoding='utf-8')

with open('C:/Users/Anatholy/.claude/projects/C--ziko-platform/395b0138-7a13-48e7-8da4-cf4d8f274b2e/tool-results/mcp-plugin_supabase_supabase-execute_sql-1778168156832.txt', 'r', encoding='utf-8') as f:
    content = f.read()

outer = json.loads(content)
text = outer[0]['text']
inner_json = json.loads(text)
result_text = inner_json['result']
idx = result_text.find('[{')
array_text = result_text[idx:]
end_idx = array_text.rfind('}]')
array_text = array_text[:end_idx+2]
exercises = json.loads(array_text)


def translate(name):
    n = name.strip().lower()

    # Full name lookup table (most common / specific names first)
    exact = {
        "3/4 sit-up": "crunch 3/4",
        "45° side bend": "inclinaison latérale 45°",
        "air bike": "vélo à air",
        "all fours squad stretch": "étirement quadriceps à quatre pattes",
        "alternate heel touchers": "touchers de talons alternés",
        "alternate lateral pulldown": "tirage latéral alterné",
        "ankle circles": "cercles de chevilles",
        "archer pull up": "traction archer",
        "archer push up": "pompe archer",
        "arm slingers hanging bent knee legs": "lanceurs de bras suspendu genoux fléchis",
        "arm slingers hanging straight legs": "lanceurs de bras suspendu jambes tendues",
        "arms apart circular toe touch (male)": "toucher circulaire des orteils bras écartés",
        "arms overhead full sit-up (male)": "crunch complet bras au-dessus de la tête",
        "assisted chest dip (kneeling)": "dips pectoraux assisté (agenouillé)",
        "assisted hanging knee raise": "relevé de genoux suspendu assisté",
        "assisted hanging knee raise with throw down": "relevé de genoux suspendu assisté avec poussée",
        "assisted lying calves stretch": "étirement mollets allongé assisté",
        "assisted lying glutes stretch": "étirement fessiers allongé assisté",
        "assisted lying gluteus and piriformis stretch": "étirement fessier et piriforme allongé assisté",
        "assisted lying leg raise with lateral throw down": "élévation de jambes allongée avec poussée latérale assistée",
        "assisted lying leg raise with throw down": "élévation de jambes allongée avec poussée assistée",
        "assisted motion russian twist": "rotation russe avec assistance",
        "assisted parallel close grip pull-up": "traction parallèle prise serrée assistée",
        "assisted prone hamstring": "ischio-jambiers couché assisté",
        "assisted prone lying quads stretch": "étirement quadriceps couché face assisté",
        "assisted prone rectus femoris stretch": "étirement droit fémoral couché face assisté",
        "assisted pull-up": "traction assistée",
        "assisted seated pectoralis major stretch with stability ball": "étirement grand pectoral assis ballon assisté",
        "assisted side lying adductor stretch": "étirement adducteur allongé sur le côté assisté",
        "assisted sit-up": "crunch assis assisté",
        "assisted standing chin-up": "traction sous-main debout assistée",
        "assisted standing pull-up": "traction debout assistée",
        "assisted standing triceps extension (with towel)": "extension triceps debout assistée (avec serviette)",
        "assisted triceps dip (kneeling)": "dips triceps assisté (agenouillé)",
        "assisted wide-grip chest dip (kneeling)": "dips pectoraux prise large assisté (agenouillé)",
        "astride jumps (male)": "sauts écart",
        "back and forth step": "pas avant-arrière",
        "back extension on exercise ball": "extension dorsale sur ballon de gym",
        "back lever": "back lever",
        "back pec stretch": "étirement dos et pectoraux",
        "backward jump": "saut en arrière",
        "balance board": "plateau d'équilibre",
        "band alternating biceps curl": "curl biceps alterné élastique",
        "band alternating v-up": "V-up alterné élastique",
        "band assisted pull-up": "traction assistée élastique",
        "band assisted wheel rollerout": "roue assistée élastique",
        "band bench press": "développé couché élastique",
        "band bent-over hip extension": "extension de hanche penché élastique",
        "band bicycle crunch": "crunch vélo élastique",
        "band close-grip pulldown": "tirage prise serrée élastique",
        "band close-grip push-up": "pompe prise serrée élastique",
        "band concentration curl": "curl concentration élastique",
        "band fixed back close grip pulldown": "tirage prise serrée dos fixe élastique",
        "band fixed back underhand pulldown": "tirage sous-main dos fixe élastique",
        "band front lateral raise": "élévation latérale-frontale élastique",
        "band front raise": "élévation frontale élastique",
        "band hip lift": "levée de hanche élastique",
        "band horizontal pallof press": "presse Pallof horizontale élastique",
        "band jack knife sit-up": "crunch jackknife élastique",
        "band kneeling one arm pulldown": "tirage un bras agenouillé élastique",
        "band kneeling twisting crunch": "crunch rotation agenouillé élastique",
        "band lying hip internal rotation": "rotation interne de hanche allongée élastique",
        "band lying straight leg raise": "élévation de jambes tendues allongée élastique",
        "band one arm overhead biceps curl": "curl biceps un bras au-dessus élastique",
        "band one arm single leg split squat": "squat fendu unipodal un bras élastique",
        "band one arm standing low row": "rowing bas debout un bras élastique",
        "band one arm twisting chest press": "développé pectoraux rotation un bras élastique",
        "band one arm twisting seated row": "rowing assis rotation un bras élastique",
        "band pull through": "passage élastique entre jambes",
        "band push sit-up": "crunch avec poussée élastique",
        "band reverse fly": "écarté arrière élastique",
        "band reverse wrist curl": "curl poignet inversé élastique",
        "band seated hip internal rotation": "rotation interne de hanche assise élastique",
        "band seated twist": "rotation assise élastique",
        "band shoulder press": "développé épaules élastique",
        "band shrug": "haussement d'épaules élastique",
        "band side triceps extension": "extension triceps latérale élastique",
        "band single leg calf raise": "élévation mollet unipodal élastique",
        "band single leg reverse calf raise": "élévation mollet inversée unipodal élastique",
        "band single leg split squat": "squat fendu unipodal élastique",
        "band squat": "squat élastique",
        "band squat row": "squat-rowing élastique",
        "band standing crunch": "crunch debout élastique",
        "band standing rear delt row": "rowing delta postérieur debout élastique",
        "band standing twisting crunch": "crunch rotation debout élastique",
        "band step-up": "pas montant élastique",
        "band stiff leg deadlift": "soulevé de terre jambes tendues élastique",
        "band straight back stiff leg deadlift": "soulevé de terre dos droit jambes tendues élastique",
        "band straight leg deadlift": "soulevé de terre jambes tendues élastique",
        "band twisting overhead press": "développé au-dessus avec rotation élastique",
        "band two legs calf raise - (band under both legs) v. 2": "élévation des mollets deux jambes élastique v. 2",
        "band underhand pulldown": "tirage sous-main élastique",
        "band v-up": "V-up élastique",
        "band vertical pallof press": "presse Pallof verticale élastique",
        "band wrist curl": "curl poignet élastique",
        "band y-raise": "élévation en Y élastique",
        "barbell alternate biceps curl": "curl biceps barre alterné",
        "barbell bench front squat": "squat avant barre sur banc",
        "barbell bench press": "développé couché barre",
        "barbell bench squat": "squat barre sur banc",
        "barbell bent arm pullover": "pullover barre bras fléchis",
        "barbell bent over row": "rowing barre penché en avant",
        "barbell biceps curl (with arm blaster)": "curl biceps barre (avec arm blaster)",
        "barbell clean and press": "épaulé-développé barre",
        "barbell clean-grip front squat": "squat avant prise épaulé barre",
        "barbell close-grip bench press": "développé couché prise serrée barre",
        "barbell curl": "curl barre",
        "barbell deadlift": "soulevé de terre barre",
        "barbell decline bench press": "développé couché décliné barre",
        "barbell decline bent arm pullover": "pullover décliné bras fléchis barre",
        "barbell decline close grip to skull press": "brise-crâne décliné prise serrée barre",
        "barbell decline pullover": "pullover décliné barre",
        "barbell decline wide-grip press": "développé décliné prise large barre",
        "barbell decline wide-grip pullover": "pullover décliné prise large barre",
        "barbell drag curl": "drag curl barre",
        "barbell floor calf raise": "élévation des mollets au sol barre",
        "barbell front chest squat": "squat avant pectoraux barre",
        "barbell front raise": "élévation frontale barre",
        "barbell front raise and pullover": "élévation frontale et pullover barre",
        "barbell front squat": "squat avant barre",
        "barbell full squat": "squat complet barre",
        "barbell full squat (back pov)": "squat complet barre (vue arrière)",
        "barbell full squat (side pov)": "squat complet barre (vue côté)",
        "barbell full zercher squat": "squat Zercher complet barre",
        "barbell glute bridge": "pont fessier barre",
        "barbell glute bridge two legs on bench (male)": "pont fessier barre deux jambes sur banc",
        "barbell good morning": "good morning barre",
        "barbell guillotine bench press": "développé couché guillotine barre",
        "barbell hack squat": "hack squat barre",
        "barbell high bar squat": "squat barre haute barre",
        "barbell incline bench press": "développé couché incliné barre",
        "barbell incline close grip bench press": "développé couché incliné prise serrée barre",
        "barbell incline reverse-grip press": "développé incliné prise inversée barre",
        "barbell incline row": "rowing incliné barre",
        "barbell incline shoulder raise": "élévation des épaules inclinée barre",
        "barbell jefferson squat": "squat Jefferson barre",
        "barbell jm bench press": "développé JM barre",
        "barbell jump squat": "squat sauté barre",
        "barbell lateral lunge": "fente latérale barre",
        "barbell low bar squat": "squat barre basse barre",
        "barbell lunge": "fente barre",
        "barbell lying back of the head tricep extension": "extension triceps derrière la tête allongée barre",
        "barbell lying close-grip press": "développé prise serrée allongé barre",
        "barbell lying close-grip triceps extension": "extension triceps prise serrée allongée barre",
        "barbell lying extension": "extension allongée barre",
        "barbell lying lifting (on hip)": "soulevé allongé sur hanche barre",
        "barbell lying preacher curl": "curl pupitre allongé barre",
        "barbell lying triceps extension": "extension triceps allongée barre",
        "barbell lying triceps extension skull crusher": "brise-crâne extension triceps allongée barre",
        "barbell narrow stance squat": "squat prise étroite barre",
        "barbell one arm bent over row": "rowing un bras penché barre",
        "barbell one arm floor press": "développé au sol un bras barre",
        "barbell one arm side deadlift": "soulevé de terre latéral un bras barre",
        "barbell one arm snatch": "arraché un bras barre",
        "barbell one leg squat": "squat unipodal barre",
        "barbell overhead squat": "squat au-dessus de la tête barre",
        "barbell palms down wrist curl over a bench": "curl poignet paumes vers le bas sur banc barre",
        "barbell palms up wrist curl over a bench": "curl poignet paumes vers le haut sur banc barre",
        "barbell pendlay row": "rowing Pendlay barre",
        "barbell pin presses": "développé en cage barre",
        "barbell preacher curl": "curl pupitre barre",
        "barbell press sit-up": "développé crunch assis barre",
        "barbell prone incline curl": "curl incliné couché face barre",
        "barbell pullover": "pullover barre",
        "barbell pullover to press": "pullover-développé barre",
        "barbell rack pull": "rack pull barre",
        "barbell rear delt raise": "élévation delta postérieur barre",
        "barbell rear delt row": "rowing delta postérieur barre",
        "barbell rear lunge": "fente arrière barre",
        "barbell rear lunge v. 2": "fente arrière barre v. 2",
        "barbell revers wrist curl v. 2": "curl poignet inversé barre v. 2",
        "barbell reverse close-grip bench press": "développé couché prise inversée serrée barre",
        "barbell reverse curl": "curl inversé barre",
        "barbell reverse grip bent over row": "rowing prise inversée penché barre",
        "barbell reverse grip decline bench press": "développé couché décliné prise inversée barre",
        "barbell reverse grip incline bench press": "développé couché incliné prise inversée barre",
        "barbell reverse grip incline bench row": "rowing incliné prise inversée barre",
        "barbell reverse grip skullcrusher": "brise-crâne prise inversée barre",
        "barbell reverse preacher curl": "curl pupitre inversé barre",
        "barbell reverse wrist curl": "curl poignet inversé barre",
        "barbell rollerout": "roue barre",
        "barbell rollerout from bench": "roue depuis banc barre",
        "barbell romanian deadlift": "soulevé de terre roumain barre",
        "barbell seated behind head military press": "développé militaire derrière la nuque assis barre",
        "barbell seated bradford rocky press": "développé Bradford assis barre",
        "barbell seated calf raise": "élévation des mollets assis barre",
        "barbell seated close grip behind neck triceps extension": "extension triceps nuque prise serrée assis barre",
        "barbell seated close-grip concentration curl": "curl concentration prise serrée assis barre",
        "barbell seated good morning": "good morning assis barre",
        "barbell seated overhead press": "développé au-dessus assis barre",
        "barbell seated overhead triceps extension": "extension triceps au-dessus assis barre",
        "barbell seated twist": "rotation assise barre",
        "barbell shrug": "haussement d'épaules barre",
        "barbell side bent v. 2": "inclinaison latérale barre v. 2",
        "barbell side split squat": "squat fendu latéral barre",
        "barbell side split squat v. 2": "squat fendu latéral barre v. 2",
        "barbell single leg deadlift": "soulevé de terre unipodal barre",
        "barbell single leg split squat": "squat fendu unipodal barre",
        "barbell sitted alternate leg raise": "élévation de jambes alternée assis barre",
        "barbell sitted alternate leg raise (female)": "élévation de jambes alternée assise barre",
        "barbell skier": "skieur barre",
        "barbell speed squat": "squat vitesse barre",
        "barbell split squat v. 2": "squat fendu barre v. 2",
        "barbell squat (on knees)": "squat agenouillé barre",
        "barbell squat jump step rear lunge": "squat sauté fente arrière barre",
        "barbell standing ab rollerout": "gainage roue debout barre",
        "barbell standing back wrist curl": "curl poignet dorsal debout barre",
        "barbell standing bradford press": "développé Bradford debout barre",
        "barbell standing calf raise": "élévation des mollets debout barre",
        "barbell standing close grip curl": "curl prise serrée debout barre",
        "barbell standing close grip military press": "développé militaire prise serrée debout barre",
        "barbell standing concentration curl": "curl concentration debout barre",
        "barbell standing front raise over head": "élévation frontale au-dessus de la tête debout barre",
        "barbell standing leg calf raise": "élévation mollet unipodal debout barre",
        "barbell standing overhead triceps extension": "extension triceps au-dessus debout barre",
        "barbell standing reverse grip curl": "curl prise inversée debout barre",
        "barbell standing rocking leg calf raise": "élévation mollet balancement unipodal barre",
        "barbell standing twist": "rotation debout barre",
        "barbell standing wide grip biceps curl": "curl biceps prise large debout barre",
        "barbell standing wide military press": "développé militaire prise large debout barre",
        "barbell standing wide-grip curl": "curl prise large debout barre",
        "barbell step-up": "pas montant barre",
        "barbell stiff leg good morning": "good morning jambes tendues barre",
        "barbell straight leg deadlift": "soulevé de terre jambes tendues barre",
        "barbell sumo deadlift": "soulevé de terre sumo barre",
        "barbell thruster": "thruster barre",
        "barbell upright row": "tirage vertical barre",
        "barbell upright row v. 2": "tirage vertical barre v. 2",
        "barbell upright row v. 3": "tirage vertical barre v. 3",
        "barbell wide bench press": "développé couché prise large barre",
        "barbell wide reverse grip bench press": "développé couché prise large inversée barre",
        "barbell wide squat": "squat prise large barre",
        "barbell wide-grip upright row": "tirage vertical prise large barre",
        "barbell wrist curl": "curl poignet barre",
        "barbell wrist curl v. 2": "curl poignet barre v. 2",
        "barbell zercher squat": "squat Zercher barre",
        "basic toe touch (male)": "toucher des orteils de base",
        "battling ropes": "cordes de combat",
        "bear crawl": "marche en ours",
        "behind head chest stretch": "étirement pectoraux derrière la tête",
        "bench dip (knees bent)": "dips sur banc genoux fléchis",
        "bench dip on floor": "dips sur banc au sol",
        "bench hip extension": "extension de hanche sur banc",
        "bench pull-ups": "tractions sur banc",
        "bent knee lying twist (male)": "rotation allongée genoux fléchis",
        "biceps leg concentration curl": "curl concentration jambes biceps",
        "biceps narrow pull-ups": "tractions prise étroite biceps",
        "biceps pull-up": "traction biceps",
        "body-up": "relevé du corps",
        "bodyweight drop jump squat": "squat sauté chute au poids du corps",
        "bodyweight incline side plank": "plank latéral incliné au poids du corps",
        "bodyweight kneeling triceps extension": "extension triceps agenouillé au poids du corps",
        "bodyweight side lying biceps curl": "curl biceps allongé sur le côté au poids du corps",
        "bodyweight squatting row": "rowing en squat au poids du corps",
        "bodyweight squatting row (with towel)": "rowing en squat au poids du corps (avec serviette)",
        "bodyweight standing calf raise": "élévation des mollets debout au poids du corps",
        "bodyweight standing close-grip one arm row": "rowing prise serrée un bras debout au poids du corps",
        "bodyweight standing close-grip row": "rowing prise serrée debout au poids du corps",
        "bodyweight standing one arm row": "rowing un bras debout au poids du corps",
        "bodyweight standing one arm row (with towel)": "rowing un bras debout au poids du corps (avec serviette)",
        "bodyweight standing row": "rowing debout au poids du corps",
        "bodyweight standing row (with towel)": "rowing debout au poids du corps (avec serviette)",
        "bottoms-up": "relevé par le bas",
        "box jump down with one leg stabilization": "saut de boîte unipodal",
        "bridge - mountain climber (cross body)": "pont - grimpeur croisé",
        "burpee": "burpee",
        "butt-ups": "relevé des fesses",
        "butterfly yoga pose": "posture papillon yoga",
        "cable alternate shoulder press": "développé épaules alterné poulie",
        "cable alternate triceps extension": "extension triceps alternée poulie",
        "cable assisted inverse leg curl": "curl jambes inversé assisté poulie",
        "cable bar lateral pulldown": "tirage latéral barre poulie",
        "cable bench press": "développé couché poulie",
        "cable close grip curl": "curl prise serrée poulie",
        "cable concentration curl": "curl concentration poulie",
        "cable concentration extension (on knee)": "extension concentration sur genou poulie",
        "cable cross-over lateral pulldown": "tirage latéral croisé poulie",
        "cable cross-over revers fly": "écarté croisé inversé poulie",
        "cable cross-over variation": "croisé poulie variation",
        "cable curl": "curl poulie",
        "cable deadlift": "soulevé de terre poulie",
        "cable decline fly": "écarté décliné poulie",
        "cable decline one arm press": "développé décliné un bras poulie",
        "cable decline press": "développé décliné poulie",
        "cable decline seated wide-grip row": "rowing assis prise large décliné poulie",
        "cable drag curl": "drag curl poulie",
        "cable floor seated wide-grip row": "rowing assis au sol prise large poulie",
        "cable forward raise": "élévation frontale poulie",
        "cable front raise": "élévation frontale poulie",
        "cable front shoulder raise": "élévation frontale épaule poulie",
        "cable hammer curl (with rope)": "curl marteau corde poulie",
        "cable high pulley overhead tricep extension": "extension triceps haute poulie au-dessus",
        "cable high row (kneeling)": "rowing haut agenouillé poulie",
        "cable hip adduction": "adduction de hanche poulie",
        "cable incline bench press": "développé couché incliné poulie",
        "cable incline bench row": "rowing incliné sur banc poulie",
        "cable incline fly": "écarté incliné poulie",
        "cable incline fly (on stability ball)": "écarté incliné sur ballon de stabilité poulie",
        "cable incline pushdown": "pushdown incliné poulie",
        "cable incline triceps extension": "extension triceps inclinée poulie",
        "cable judo flip": "projection judo poulie",
        "cable kickback": "kick-back poulie",
        "cable kneeling crunch": "crunch agenouillé poulie",
        "cable kneeling rear delt row (with rope) (male)": "rowing delta postérieur agenouillé corde poulie",
        "cable kneeling triceps extension": "extension triceps agenouillé poulie",
        "cable lat pulldown full range of motion": "tirage dorsaux pleine amplitude poulie",
        "cable lateral pulldown (with rope attachment)": "tirage latéral corde poulie",
        "cable lateral pulldown with v-bar": "tirage latéral barre V poulie",
        "cable lateral raise": "élévation latérale poulie",
        "cable low fly": "écarté bas poulie",
        "cable low seated row": "rowing assis bas poulie",
        "cable lying bicep curl": "curl biceps allongé poulie",
        "cable lying close-grip curl": "curl prise serrée allongé poulie",
        "cable lying extension pullover (with rope attachment)": "extension-pullover allongé corde poulie",
        "cable lying fly": "écarté allongé poulie",
        "cable lying triceps extension v. 2": "extension triceps allongée poulie v. 2",
        "cable middle fly": "écarté milieu poulie",
        "cable one arm bent over row": "rowing un bras penché poulie",
        "cable one arm curl": "curl un bras poulie",
        "cable one arm decline chest fly": "écarté pectoraux décliné un bras poulie",
        "cable one arm fly on exercise ball": "écarté un bras sur ballon poulie",
        "cable one arm incline fly on exercise ball": "écarté incliné un bras sur ballon poulie",
        "cable one arm incline press": "développé incliné un bras poulie",
        "cable one arm incline press on exercise ball": "développé incliné un bras sur ballon poulie",
        "cable one arm lateral bent-over": "inclinaison latérale un bras poulie",
        "cable one arm lateral raise": "élévation latérale un bras poulie",
        "cable one arm preacher curl": "curl pupitre un bras poulie",
        "cable one arm press on exercise ball": "développé un bras sur ballon poulie",
        "cable one arm pulldown": "tirage un bras poulie",
        "cable one arm reverse preacher curl": "curl pupitre inversé un bras poulie",
        "cable one arm straight back high row (kneeling)": "rowing haut dos droit un bras agenouillé poulie",
        "cable one arm tricep pushdown": "triceps pushdown un bras poulie",
        "cable overhead curl": "curl au-dessus poulie",
        "cable overhead curl on exercise ball": "curl au-dessus sur ballon poulie",
        "cable overhead triceps extension (rope attachment)": "extension triceps au-dessus corde poulie",
        "cable palm rotational row": "rowing rotation palmaire poulie",
        "cable preacher curl": "curl pupitre poulie",
        "cable press on exercise ball": "développé sur ballon poulie",
        "cable pull through (with rope)": "passage corde entre jambes poulie",
        "cable pulldown": "tirage poulie vers le bas",
        "cable pulldown (pro lat bar)": "tirage dorsaux barre pro poulie",
        "cable pulldown bicep curl": "tirage curl biceps poulie",
        "cable pushdown": "pushdown poulie",
        "cable pushdown (straight arm) v. 2": "pushdown bras tendu poulie v. 2",
        "cable pushdown (with rope attachment)": "pushdown corde poulie",
        "cable rear delt row (stirrups)": "rowing delta postérieur étriers poulie",
        "cable rear delt row (with rope)": "rowing delta postérieur corde poulie",
        "cable rear drive": "propulsion arrière poulie",
        "cable rear pulldown": "tirage arrière poulie",
        "cable reverse crunch": "crunch inversé poulie",
        "cable reverse curl": "curl inversé poulie",
        "cable reverse grip triceps pushdown (sz-bar) (with arm blaster)": "triceps pushdown prise inversée barre SZ poulie",
        "cable reverse one arm curl": "curl inversé un bras poulie",
        "cable reverse preacher curl": "curl pupitre inversé poulie",
        "cable reverse wrist curl": "curl poignet inversé poulie",
        "cable reverse-grip pushdown": "pushdown prise inversée poulie",
        "cable reverse-grip straight back seated high row": "rowing haut assis dos droit prise inversée poulie",
        "cable rope crossover seated row": "rowing assis croisé corde poulie",
        "cable rope elevated seated row": "rowing assis surélevé corde poulie",
        "cable rope extension incline bench row": "rowing incliné extension corde poulie",
        "cable rope hammer preacher curl": "curl pupitre marteau corde poulie",
        "cable rope high pulley overhead tricep extension": "extension triceps haute poulie corde au-dessus",
        "cable rope incline tricep extension": "extension triceps inclinée corde poulie",
        "cable rope lying on floor tricep extension": "extension triceps allongée au sol corde poulie",
        "cable rope one arm hammer preacher curl": "curl pupitre marteau un bras corde poulie",
        "cable rope seated row": "rowing assis corde poulie",
        "cable russian twists (on stability ball)": "rotations russes sur ballon de stabilité poulie",
        "cable seated chest press": "développé pectoraux assis poulie",
        "cable seated crunch": "crunch assis poulie",
        "cable seated curl": "curl assis poulie",
        "cable seated high row (v-bar)": "rowing haut assis barre V poulie",
        "cable seated one arm alternate row": "rowing alterné un bras assis poulie",
        "cable seated one arm concentration curl": "curl concentration un bras assis poulie",
        "cable seated overhead curl": "curl au-dessus assis poulie",
        "cable seated rear lateral raise": "élévation latérale arrière assise poulie",
        "cable seated row": "rowing assis poulie",
        "cable seated shoulder internal rotation": "rotation interne épaule assise poulie",
        "cable seated twist": "rotation assise poulie",
        "cable seated wide-grip row": "rowing assis prise large poulie",
        "cable shoulder press": "développé épaules poulie",
        "cable shrug": "haussement d'épaules poulie",
        "cable side bend": "inclinaison latérale poulie",
        "cable side bend crunch (bosu ball)": "crunch inclinaison latérale bosu poulie",
        "cable side crunch": "crunch latéral poulie",
        "cable squat row (with rope attachment)": "squat-rowing corde poulie",
        "cable squatting curl": "curl en squat poulie",
        "cable standing back wrist curl": "curl poignet dorsal debout poulie",
        "cable standing calf raise": "élévation des mollets debout poulie",
        "cable standing cross-over high reverse fly": "écarté inversé haut croisé debout poulie",
        "cable standing crunch": "crunch debout poulie",
        "cable standing crunch (with rope attachment)": "crunch debout corde poulie",
        "cable standing fly": "écarté debout poulie",
        "cable standing hip extension": "extension de hanche debout poulie",
        "cable standing inner curl": "curl intérieur debout poulie",
        "cable standing lift": "soulevé debout poulie",
        "cable standing one arm triceps extension": "extension triceps un bras debout poulie",
        "cable standing one leg calf raise": "élévation mollet unipodal debout poulie",
        "cable standing pulldown (with rope)": "tirage debout corde poulie",
        "cable standing rear delt row (with rope)": "rowing delta postérieur debout corde poulie",
        "cable standing reverse grip one arm overhead tricep extension": "extension triceps un bras prise inversée au-dessus debout poulie",
        "cable standing row (v-bar)": "rowing debout barre V poulie",
        "cable standing shoulder external rotation": "rotation externe épaule debout poulie",
        "cable standing twist row (v-bar)": "rowing rotation debout barre V poulie",
        "cable standing up straight crossovers": "croisé debout droit poulie",
        "cable straight arm pulldown": "tirage bras tendus poulie",
        "cable straight arm pulldown (with rope)": "tirage bras tendus corde poulie",
        "cable straight back seated row": "rowing assis dos droit poulie",
        "cable supine reverse fly": "écarté inversé couché sur le dos poulie",
        "cable thibaudeau kayak row": "rowing kayak Thibaudeau poulie",
        "cable triceps pushdown (v-bar)": "triceps pushdown barre V poulie",
        "cable triceps pushdown (v-bar) (with arm blaster)": "triceps pushdown barre V arm blaster poulie",
        "cable tuck reverse crunch": "crunch inversé ramassé poulie",
        "cable twist": "rotation poulie",
        "cable twist (up-down)": "rotation haut-bas poulie",
        "cable twisting pull": "tirage rotation poulie",
        "cable two arm curl on incline bench": "curl deux bras sur banc incliné poulie",
        "cable two arm tricep kickback": "kick-back triceps deux bras poulie",
        "cable underhand pulldown": "tirage sous-main poulie",
        "cable upper chest crossovers": "croisé haut des pectoraux poulie",
        "cable upper row": "rowing haut poulie",
        "cable upright row": "tirage vertical poulie",
        "cable wide grip rear pulldown behind neck": "tirage nuque prise large poulie",
        "cable wrist curl": "curl poignet poulie",
        "calf push stretch with hands against wall": "étirement mollets mains contre le mur",
        "calf stretch with hands against wall": "étirement mollets mains contre le mur",
        "calf stretch with rope": "étirement mollets avec corde",
        "cambered bar lying row": "rowing allongé barre cambrée",
        "captains chair straight leg raise": "élévation jambes tendues chaise capitaine",
        "chair leg extended stretch": "étirement jambe tendue sur chaise",
        "chest and front of shoulder stretch": "étirement pectoraux et épaules avant",
        "chest dip": "dips pectoraux",
        "chest dip (on dip-pull-up cage)": "dips pectoraux (sur cage)",
        "chest dip on straight bar": "dips pectoraux barre droite",
        "chest stretch with exercise ball": "étirement pectoraux avec ballon de gym",
        "chest tap push-up (male)": "pompe avec tape sur les pectoraux",
        "chin-up": "traction sous-main",
        "chin-ups (narrow parallel grip)": "tractions prise parallèle étroite",
        "circles knee stretch": "étirement circulaire des genoux",
        "clap push up": "pompe avec claquement",
        "clock push-up": "pompe horloge",
        "close grip chin-up": "traction prise serrée sous-main",
        "close-grip push-up": "pompe prise serrée",
        "close-grip push-up (on knees)": "pompe prise serrée sur les genoux",
        "cocoons": "cocons (crunch genoux-coudes)",
        "crab twist toe touch": "toucher des orteils rotation crabe",
        "cross body crunch": "crunch croisé",
        "crunch (hands overhead)": "crunch bras au-dessus de la tête",
        "crunch (on stability ball, arms straight)": "crunch sur ballon de stabilité bras tendus",
        "crunch (on stability ball)": "crunch sur ballon de stabilité",
        "crunch floor": "crunch au sol",
        "curl-up": "relevé en curl",
        "curtsey squat": "squat révérence",
        "cycle cross trainer": "vélo elliptique",
        "dead bug": "dead bug",
        "decline crunch": "crunch décliné",
        "decline push-up": "pompe déclinée",
        "decline sit-up": "crunch assis décliné",
        "deep push up": "pompe profonde",
        "diamond push-up": "pompe diamant",
        "donkey calf raise": "élévation des mollets en âne",
        "drop push up": "pompe à lâcher",
        "dumbbell alternate biceps curl": "curl biceps haltère alterné",
        "dumbbell alternate biceps curl (with arm blaster)": "curl biceps haltère alterné (avec arm blaster)",
        "dumbbell alternate hammer preacher curl": "curl marteau pupitre haltère alterné",
        "dumbbell alternate preacher curl": "curl pupitre haltère alterné",
        "dumbbell alternate seated hammer curl": "curl marteau assis haltère alterné",
        "dumbbell alternate side press": "développé latéral haltère alterné",
        "dumbbell alternating bicep curl with leg raised on exercise ball": "curl biceps haltère alterné jambe levée sur ballon",
        "dumbbell alternating seated bicep curl on exercise ball": "curl biceps assis haltère alterné sur ballon",
        "dumbbell arnold press": "développé Arnold haltères",
        "dumbbell arnold press v. 2": "développé Arnold haltères v. 2",
        "dumbbell around pullover": "pullover circulaire haltère",
        "dumbbell bench press": "développé couché haltères",
        "dumbbell bench seated press": "développé assis sur banc haltères",
        "dumbbell bench squat": "squat sur banc haltères",
        "dumbbell bent over row": "rowing haltère penché en avant",
        "dumbbell bicep curl lunge with bowling motion": "curl biceps fente avec mouvement bowling haltère",
        "dumbbell bicep curl on exercise ball with leg raised": "curl biceps sur ballon jambe levée haltère",
        "dumbbell bicep curl with stork stance": "curl biceps sur une jambe haltère",
        "dumbbell biceps curl": "curl biceps haltère",
        "dumbbell biceps curl (with arm blaster)": "curl biceps haltère (avec arm blaster)",
        "dumbbell biceps curl reverse": "curl biceps inversé haltère",
        "dumbbell biceps curl squat": "curl biceps squat haltère",
        "dumbbell biceps curl v sit on bosu ball": "curl biceps V-sit bosu haltère",
        "dumbbell burpee": "burpee haltères",
        "dumbbell clean": "épaulé haltères",
        "dumbbell close grip press": "développé prise serrée haltères",
        "dumbbell close-grip press": "développé prise serrée haltères",
        "dumbbell concentration curl": "curl concentration haltère",
        "dumbbell contralateral forward lunge": "fente avant controlatérale haltères",
        "dumbbell cross body hammer curl": "curl marteau croisé haltère",
        "dumbbell cross body hammer curl v. 2": "curl marteau croisé haltère v. 2",
        "dumbbell cuban press": "développé cubain haltères",
        "dumbbell cuban press v. 2": "développé cubain haltères v. 2",
        "dumbbell deadlift": "soulevé de terre haltères",
        "dumbbell decline bench press": "développé couché décliné haltères",
        "dumbbell decline fly": "écarté décliné haltères",
        "dumbbell decline hammer press": "développé marteau décliné haltères",
        "dumbbell decline one arm fly": "écarté décliné un bras haltères",
        "dumbbell decline one arm hammer press": "développé marteau décliné un bras haltères",
        "dumbbell decline shrug": "haussement d'épaules décliné haltères",
        "dumbbell decline shrug v. 2": "haussement d'épaules décliné haltères v. 2",
        "dumbbell decline triceps extension": "extension triceps déclinée haltères",
        "dumbbell decline twist fly": "écarté décliné rotation haltères",
        "dumbbell finger curls": "curl des doigts haltère",
        "dumbbell fly": "écarté haltères",
        "dumbbell fly on exercise ball": "écarté sur ballon haltères",
        "dumbbell forward lunge triceps extension": "fente avant extension triceps haltères",
        "dumbbell front raise": "élévation frontale haltère",
        "dumbbell front raise v. 2": "élévation frontale haltère v. 2",
        "dumbbell full can lateral raise": "élévation latérale boîte pleine haltère",
        "dumbbell goblet squat": "goblet squat haltère",
        "dumbbell hammer curl": "curl marteau haltère",
        "dumbbell hammer curl on exercise ball": "curl marteau sur ballon haltère",
        "dumbbell hammer curl v. 2": "curl marteau haltère v. 2",
        "dumbbell hammer curls (with arm blaster)": "curl marteau haltères (avec arm blaster)",
        "dumbbell high curl": "curl haut haltère",
        "dumbbell incline alternate press": "développé incliné alterné haltères",
        "dumbbell incline bench press": "développé couché incliné haltères",
        "dumbbell incline biceps curl": "curl biceps incliné haltère",
        "dumbbell incline breeding": "écarté incliné haltères",
        "dumbbell incline curl": "curl incliné haltère",
        "dumbbell incline curl v. 2": "curl incliné haltère v. 2",
        "dumbbell incline fly": "écarté incliné haltères",
        "dumbbell incline fly on exercise ball": "écarté incliné sur ballon haltères",
        "dumbbell incline hammer curl": "curl marteau incliné haltère",
        "dumbbell incline hammer press": "développé marteau incliné haltères",
        "dumbbell incline hammer press on exercise ball": "développé marteau incliné sur ballon haltères",
        "dumbbell incline inner biceps curl": "curl biceps intérieur incliné haltère",
        "dumbbell incline one arm fly": "écarté incliné un bras haltères",
        "dumbbell incline one arm fly on exercise ball": "écarté incliné un bras sur ballon haltères",
        "dumbbell incline one arm hammer press": "développé marteau incliné un bras haltères",
        "dumbbell incline one arm hammer press on exercise ball": "développé marteau incliné un bras sur ballon haltères",
        "dumbbell incline one arm lateral raise": "élévation latérale inclinée un bras haltère",
        "dumbbell incline one arm press": "développé incliné un bras haltères",
        "dumbbell incline one arm press on exercise ball": "développé incliné un bras sur ballon haltères",
        "dumbbell incline palm-in press": "développé incliné paumes face haltères",
        "dumbbell incline press on exercise ball": "développé incliné sur ballon haltères",
        "dumbbell incline raise": "élévation inclinée haltère",
        "dumbbell incline rear lateral raise": "élévation latérale arrière inclinée haltères",
        "dumbbell incline row": "rowing incliné haltères",
        "dumbbell incline shoulder raise": "élévation épaule inclinée haltère",
        "dumbbell incline shrug": "haussement d'épaules incliné haltères",
        "dumbbell incline t-raise": "élévation en T inclinée haltère",
        "dumbbell incline triceps extension": "extension triceps inclinée haltères",
        "dumbbell incline twisted flyes": "écarté twisté incliné haltères",
        "dumbbell incline two arm extension": "extension deux bras inclinée haltères",
        "dumbbell incline y-raise": "élévation en Y inclinée haltère",
        "dumbbell iron cross": "croix de fer haltères",
        "dumbbell kickback": "kick-back haltère",
        "dumbbell kickbacks on exercise ball": "kick-back sur ballon haltère",
        "dumbbell kneeling bicep curl exercise ball": "curl biceps agenouillé sur ballon haltère",
        "dumbbell lateral raise": "élévation latérale haltère",
        "dumbbell lateral to front raise": "élévation latérale vers frontale haltère",
        "dumbbell lunge": "fente haltère",
        "dumbbell lunge with bicep curl": "fente avec curl biceps haltère",
        "dumbbell lying alternate extension": "extension alternée allongée haltère",
        "dumbbell lying elbow press": "développé coude allongé haltère",
        "dumbbell lying extension (across face)": "extension allongée (en travers du visage) haltère",
        "dumbbell lying external shoulder rotation": "rotation externe épaule allongée haltère",
        "dumbbell lying femoral": "ischio-jambiers allongé haltère",
        "dumbbell lying hammer press": "développé marteau allongé haltère",
        "dumbbell lying on floor rear delt raise": "élévation delta postérieur allongé au sol haltère",
        "dumbbell lying one arm deltoid rear": "élévation delta postérieur un bras allongé haltère",
        "dumbbell lying one arm press": "développé un bras allongé haltère",
        "dumbbell lying one arm press v. 2": "développé un bras allongé haltère v. 2",
        "dumbbell lying one arm pronated triceps extension": "extension triceps un bras en pronation allongé haltère",
        "dumbbell lying one arm rear lateral raise": "élévation latérale arrière un bras allongé haltère",
        "dumbbell lying one arm supinated triceps extension": "extension triceps un bras en supination allongé haltère",
        "dumbbell lying pronation": "pronation allongée haltère",
        "dumbbell lying pronation on floor": "pronation allongée au sol haltère",
        "dumbbell lying pullover on exercise ball": "pullover allongé sur ballon haltère",
        "dumbbell lying rear delt row": "rowing delta postérieur allongé haltère",
        "dumbbell lying rear lateral raise": "élévation latérale arrière allongée haltère",
        "dumbbell lying single extension": "extension unique allongée haltère",
        "dumbbell lying supination": "supination allongée haltère",
        "dumbbell lying supination on floor": "supination allongée au sol haltère",
        "dumbbell lying supine biceps curl": "curl biceps couché sur le dos haltère",
        "dumbbell lying supine curl": "curl couché sur le dos haltère",
        "dumbbell lying triceps extension": "extension triceps allongée haltères",
        "dumbbell lying wide curl": "curl large allongé haltère",
        "dumbbell neutral grip bench press": "développé couché prise neutre haltères",
        "dumbbell one arm bench fly": "écarté un bras sur banc haltère",
        "dumbbell one arm bent-over row": "rowing un bras penché haltère",
        "dumbbell one arm chest fly on exercise ball": "écarté pectoraux un bras sur ballon haltère",
        "dumbbell one arm concentration curl (on stability ball)": "curl concentration un bras sur ballon de stabilité haltère",
        "dumbbell one arm decline chest press": "développé pectoraux décliné un bras haltère",
        "dumbbell one arm fly on exercise ball": "écarté un bras sur ballon haltère",
        "dumbbell one arm french press on exercise ball": "développé français un bras sur ballon haltère",
        "dumbbell one arm hammer preacher curl": "curl marteau pupitre un bras haltère",
        "dumbbell one arm hammer press on exercise ball": "développé marteau un bras sur ballon haltère",
        "dumbbell one arm incline chest press": "développé pectoraux incliné un bras haltère",
        "dumbbell one arm kickback": "kick-back un bras haltère",
        "dumbbell one arm lateral raise": "élévation latérale un bras haltère",
        "dumbbell one arm lateral raise with support": "élévation latérale un bras avec appui haltère",
        "dumbbell one arm press on exercise ball": "développé un bras sur ballon haltère",
        "dumbbell one arm prone curl": "curl couché face un bras haltère",
        "dumbbell one arm prone hammer curl": "curl marteau couché face un bras haltère",
        "dumbbell one arm pullover on exercise ball": "pullover un bras sur ballon haltère",
        "dumbbell one arm reverse fly (with support)": "écarté inversé un bras avec appui haltère",
        "dumbbell one arm reverse grip press": "développé prise inversée un bras haltère",
        "dumbbell one arm reverse preacher curl": "curl pupitre inversé un bras haltère",
        "dumbbell one arm reverse spider curl": "curl araignée inversé un bras haltère",
        "dumbbell one arm reverse wrist curl": "curl poignet inversé un bras haltère",
        "dumbbell one arm seated bicep curl on exercise ball with leg raised": "curl biceps assis sur ballon jambe levée un bras haltère",
        "dumbbell one arm seated hammer curl": "curl marteau assis un bras haltère",
        "dumbbell one arm seated neutral wrist curl": "curl poignet neutre assis un bras haltère",
        "dumbbell one arm shoulder press": "développé épaules un bras haltère",
        "dumbbell one arm shoulder press v. 2": "développé épaules un bras haltère v. 2",
        "dumbbell one arm snatch": "arraché un bras haltère",
        "dumbbell one arm standing curl": "curl debout un bras haltère",
        "dumbbell one arm standing hammer curl": "curl marteau debout un bras haltère",
        "dumbbell one arm triceps extension (on bench)": "extension triceps un bras sur banc haltère",
        "dumbbell one arm upright row": "tirage vertical un bras haltère",
        "dumbbell one arm wrist curl": "curl poignet un bras haltère",
        "dumbbell one arm zottman preacher curl": "curl Zottman pupitre un bras haltère",
        "dumbbell one leg fly on exercise ball": "écarté unipodal sur ballon haltère",
        "dumbbell over bench neutral wrist curl": "curl poignet neutre sur banc haltère",
        "dumbbell over bench one arm neutral wrist curl": "curl poignet neutre un bras sur banc haltère",
        "dumbbell over bench one arm reverse wrist curl": "curl poignet inversé un bras sur banc haltère",
        "dumbbell over bench one arm wrist curl": "curl poignet un bras sur banc haltère",
        "dumbbell over bench revers wrist curl": "curl poignet inversé sur banc haltère",
        "dumbbell over bench wrist curl": "curl poignet sur banc haltère",
        "dumbbell palm rotational bent over row": "rowing penché rotation palmaire haltère",
        "dumbbell palms in incline bench press": "développé couché incliné paumes face haltères",
        "dumbbell peacher hammer curl": "curl marteau pupitre haltère",
        "dumbbell plyo squat": "squat pliométrique haltères",
        "dumbbell preacher curl": "curl pupitre haltère",
        "dumbbell preacher curl over exercise ball": "curl pupitre sur ballon haltère",
        "dumbbell press on exercise ball": "développé sur ballon haltères",
        "dumbbell pronate-grip triceps extension": "extension triceps prise pronation haltères",
        "dumbbell prone incline curl": "curl incliné couché face haltère",
        "dumbbell prone incline hammer curl": "curl marteau incliné couché face haltère",
        "dumbbell pullover": "pullover haltère",
        "dumbbell pullover hip extension on exercise ball": "pullover extension de hanche sur ballon haltère",
        "dumbbell pullover on exercise ball": "pullover sur ballon haltère",
        "dumbbell push press": "push press haltères",
        "dumbbell raise": "élévation haltère",
        "dumbbell rear delt raise": "élévation delta postérieur haltères",
        "dumbbell rear delt row_shoulder": "rowing delta postérieur épaule haltères",
        "dumbbell rear fly": "écarté arrière haltères",
        "dumbbell rear lateral raise": "élévation latérale arrière haltères",
        "dumbbell rear lateral raise (support head)": "élévation latérale arrière haltères (tête appuyée)",
        "dumbbell rear lunge": "fente arrière haltères",
        "dumbbell revers grip biceps curl": "curl biceps prise inversée haltère",
        "dumbbell reverse bench press": "développé couché inversé haltères",
        "dumbbell reverse fly": "écarté inversé haltères",
        "dumbbell reverse grip incline bench one arm row": "rowing incliné prise inversée un bras haltère",
        "dumbbell reverse grip incline bench two arm row": "rowing incliné prise inversée deux bras haltères",
        "dumbbell reverse grip row (female)": "rowing prise inversée haltère",
        "dumbbell reverse preacher curl": "curl pupitre inversé haltère",
        "dumbbell reverse spider curl": "curl araignée inversé haltère",
        "dumbbell reverse wrist curl": "curl poignet inversé haltère",
        "dumbbell romanian deadlift": "soulevé de terre roumain haltères",
        "dumbbell rotation reverse fly": "écarté inversé rotation haltères",
        "dumbbell scott press": "développé Scott haltères",
        "dumbbell seated alternate front raise": "élévation frontale alternée assise haltère",
        "dumbbell seated alternate hammer curl on exercise ball": "curl marteau alterné assis sur ballon haltère",
        "dumbbell seated alternate press": "développé alterné assis haltères",
        "dumbbell seated alternate shoulder": "élévation épaule alternée assise haltère",
        "dumbbell seated bench extension": "extension sur banc assis haltère",
        "dumbbell seated bent arm lateral raise": "élévation latérale bras fléchi assis haltère",
        "dumbbell seated bent over alternate kickback": "kick-back alterné penché assis haltère",
        "dumbbell seated bent over triceps extension": "extension triceps penché assis haltère",
        "dumbbell seated bicep curl": "curl biceps assis haltère",
        "dumbbell seated biceps curl (on stability ball)": "curl biceps assis sur ballon de stabilité haltère",
        "dumbbell seated biceps curl to shoulder press": "curl biceps développé épaules assis haltère",
        "dumbbell seated calf raise": "élévation des mollets assis haltère",
        "dumbbell seated curl": "curl assis haltère",
        "dumbbell seated front raise": "élévation frontale assise haltère",
        "dumbbell seated hammer curl": "curl marteau assis haltère",
        "dumbbell seated inner biceps curl": "curl biceps intérieur assis haltère",
        "dumbbell seated kickback": "kick-back assis haltère",
        "dumbbell seated lateral raise": "élévation latérale assise haltère",
        "dumbbell seated lateral raise v. 2": "élévation latérale assise haltère v. 2",
        "dumbbell seated neutral wrist curl": "curl poignet neutre assis haltère",
        "dumbbell seated one arm bicep curl on exercise ball with leg raised": "curl biceps un bras assis sur ballon jambe levée haltère",
        "dumbbell seated one arm kickback": "kick-back un bras assis haltère",
        "dumbbell seated one arm rotate": "rotation un bras assis haltère",
        "dumbbell seated one leg calf raise": "élévation mollet unipodal assis haltère",
        "dumbbell seated one leg calf raise - hammer grip": "élévation mollet unipodal prise marteau assis haltère",
        "dumbbell seated one leg calf raise - palm up": "élévation mollet unipodal paume vers le haut assis haltère",
        "dumbbell seated palms up wrist curl": "curl poignet paumes vers le haut assis haltère",
        "dumbbell seated preacher curl": "curl pupitre assis haltère",
        "dumbbell seated revers grip concentration curl": "curl concentration prise inversée assis haltère",
        "dumbbell seated reverse grip one arm overhead tricep extension": "extension triceps un bras prise inversée au-dessus assis haltère",
        "dumbbell seated shoulder press": "développé épaules assis haltères",
        "dumbbell seated shoulder press (parallel grip)": "développé épaules assis prise parallèle haltères",
        "dumbbell seated triceps extension": "extension triceps assis haltères",
        "dumbbell shrug": "haussement d'épaules haltères",
        "dumbbell side bend": "inclinaison latérale haltère",
        "dumbbell side lying one hand raise": "élévation d'un bras allongé sur le côté haltère",
        "dumbbell side plank with rear fly": "plank latéral avec écarté arrière haltère",
        "dumbbell single arm overhead carry": "portage au-dessus un bras haltère",
        "dumbbell single leg calf raise": "élévation mollet unipodal haltère",
        "dumbbell single leg deadlift": "soulevé de terre unipodal haltère",
        "dumbbell single leg deadlift with stepbox support": "soulevé de terre unipodal avec support haltère",
        "dumbbell single leg split squat": "squat fendu unipodal haltères",
        "dumbbell single leg squat": "squat unipodal haltères",
        "dumbbell squat": "squat haltères",
        "dumbbell standing alternate hammer curl and press": "curl marteau et développé alterné debout haltère",
        "dumbbell standing alternate overhead press": "développé au-dessus alterné debout haltères",
        "dumbbell standing alternate raise": "élévation alternée debout haltère",
        "dumbbell standing alternating tricep kickback": "kick-back triceps alterné debout haltère",
        "dumbbell standing around world": "tour du monde debout haltères",
        "dumbbell standing bent over one arm triceps extension": "extension triceps un bras penché debout haltère",
        "dumbbell standing bent over two arm triceps extension": "extension triceps deux bras penché debout haltères",
        "dumbbell standing biceps curl": "curl biceps debout haltère",
        "dumbbell standing calf raise": "élévation des mollets debout haltère",
        "dumbbell standing concentration curl": "curl concentration debout haltère",
        "dumbbell standing front raise above head": "élévation frontale au-dessus de la tête debout haltère",
        "dumbbell standing inner biceps curl v. 2": "curl biceps intérieur debout haltère v. 2",
        "dumbbell standing kickback": "kick-back debout haltère",
        "dumbbell standing one arm concentration curl": "curl concentration un bras debout haltère",
        "dumbbell standing one arm curl (over incline bench)": "curl un bras sur banc incliné debout haltère",
        "dumbbell standing one arm curl over incline bench": "curl un bras sur banc incliné debout haltère",
        "dumbbell standing one arm extension": "extension un bras debout haltère",
        "dumbbell standing one arm palm in press": "développé paume face un bras debout haltère",
        "dumbbell standing one arm reverse curl": "curl inversé un bras debout haltère",
        "dumbbell standing overhead press": "développé au-dessus de la tête debout haltères",
        "dumbbell standing palms in press": "développé paumes face debout haltères",
        "dumbbell standing preacher curl": "curl pupitre debout haltère",
        "dumbbell standing reverse curl": "curl inversé debout haltère",
        "dumbbell standing triceps extension": "extension triceps debout haltères",
        "dumbbell standing zottman preacher curl": "curl Zottman pupitre debout haltère",
        "dumbbell step up single leg balance with bicep curl": "pas montant équilibre unipodal avec curl biceps haltère",
        "dumbbell step-up": "pas montant haltères",
        "dumbbell step-up lunge": "pas montant fente haltères",
        "dumbbell step-up split squat": "pas montant squat fendu haltères",
        "dumbbell stiff leg deadlift": "soulevé de terre jambes tendues haltères",
        "dumbbell straight arm pullover": "pullover bras tendus haltère",
        "dumbbell straight leg deadlift": "soulevé de terre jambes tendues haltères",
        "dumbbell sumo pull through": "passage sumo haltères",
        "dumbbell supported squat": "squat avec appui haltères",
        "dumbbell tate press": "développé Tate haltères",
        "dumbbell tricep kickback with stork stance": "kick-back triceps sur une jambe haltère",
        "dumbbell twisting bench press": "développé couché twisté haltères",
        "dumbbell upright row": "tirage vertical haltères",
        "dumbbell upright row (back pov)": "tirage vertical haltères (vue arrière)",
        "dumbbell upright shoulder external rotation": "rotation externe épaule debout haltère",
        "dumbbell w-press": "développé en W haltères",
        "dumbbell waiter biceps curl": "curl biceps serveur haltère",
        "dumbbell zottman curl": "curl Zottman haltère",
        "dumbbell zottman preacher curl": "curl Zottman pupitre haltère",
        "dumbbells seated triceps extension": "extension triceps assis haltères",
        "dynamic chest stretch (male)": "étirement pectoraux dynamique",
        "elbow dips": "dips sur coudes",
        "elbow lift - reverse push-up": "relevé coude - pompe inversée",
        "elbow-to-knee": "coude au genou",
        "elevator": "ascenseur (gainage)",
        "exercise ball alternating arm ups": "élévations de bras alternées sur ballon",
        "exercise ball back extension with arms extended": "extension dorsale sur ballon bras tendus",
        "exercise ball back extension with hands behind head": "extension dorsale sur ballon mains derrière la tête",
        "exercise ball back extension with knees off ground": "extension dorsale sur ballon genoux décollés",
        "exercise ball back extension with rotation": "extension dorsale sur ballon avec rotation",
        "exercise ball dip": "dips sur ballon",
        "exercise ball hip flexor stretch": "étirement fléchisseur de hanche sur ballon",
        "exercise ball hug": "enlacement du ballon",
        "exercise ball lat stretch": "étirement dorsal sur ballon",
        "exercise ball lower back stretch (pyramid)": "étirement bas du dos sur ballon (pyramide)",
        "exercise ball lying side lat stretch": "étirement dorsal latéral allongé sur ballon",
        "exercise ball on the wall calf raise": "élévation des mollets sur ballon contre le mur",
        "exercise ball on the wall calf raise (tennis ball between ankles)": "élévation des mollets sur ballon mur (balle tennis aux chevilles)",
        "exercise ball on the wall calf raise (tennis ball between knees)": "élévation des mollets sur ballon mur (balle tennis aux genoux)",
        "exercise ball one leg prone lower body rotation": "rotation bas du corps couché face unipodal sur ballon",
        "exercise ball one legged diagonal kick hamstring curl": "curl ischio-jambier kick diagonal unipodal sur ballon",
        "exercise ball pike push up": "pompe en pique sur ballon",
        "exercise ball prone leg raise": "élévation de jambes couché face sur ballon",
        "exercise ball seated hamstring stretch": "étirement ischio-jambiers assis sur ballon",
        "exercise ball seated triceps stretch": "étirement triceps assis sur ballon",
        "exercise ball supine triceps extension": "extension triceps couché sur le dos sur ballon",
        "ez bar french press on exercise ball": "développé français barre EZ sur ballon",
        "ez bar lying bent arms pullover": "pullover allongé bras fléchis barre EZ",
        "ez bar lying close grip triceps extension behind head": "extension triceps derrière la tête prise serrée allongée barre EZ",
        "ez bar reverse grip bent over row": "rowing penché prise inversée barre EZ",
        "ez bar seated close grip concentration curl": "curl concentration prise serrée assis barre EZ",
        "ez bar standing french press": "développé français debout barre EZ",
        "ez barbell anti gravity press": "développé anti-gravité barre EZ",
        "ez barbell close grip preacher curl": "curl pupitre prise serrée barre EZ",
        "ez barbell close-grip curl": "curl prise serrée barre EZ",
        "ez barbell curl": "curl barre EZ",
        "ez barbell decline close grip face press": "développé décliné prise serrée face barre EZ",
        "ez barbell decline triceps extension": "extension triceps déclinée barre EZ",
        "ez barbell incline triceps extension": "extension triceps inclinée barre EZ",
        "ez barbell jm bench press": "développé JM barre EZ",
        "ez barbell reverse grip curl": "curl prise inversée barre EZ",
        "ez barbell reverse grip preacher curl": "curl pupitre prise inversée barre EZ",
        "ez barbell seated curls": "curl assis barre EZ",
        "ez barbell seated triceps extension": "extension triceps assis barre EZ",
        "ez barbell spider curl": "curl araignée barre EZ",
        "ez-bar biceps curl (with arm blaster)": "curl biceps barre EZ (avec arm blaster)",
        "ez-bar close-grip bench press": "développé couché prise serrée barre EZ",
        "ez-barbell standing wide grip biceps curl": "curl biceps prise large debout barre EZ",
        "farmers walk": "farmer walk",
        "finger curls": "curl des doigts",
        "flag": "flag (gainage)",
        "flexion leg sit up (bent knee)": "crunch genoux fléchis",
        "flexion leg sit up (straight arm)": "crunch bras tendus jambes fléchies",
        "floor fly (with barbell)": "écarté au sol (avec barre)",
        "flutter kicks": "battements de jambes",
        "forward jump": "saut en avant",
        "forward lunge (male)": "fente avant",
        "frankenstein squat": "squat Frankenstein",
        "frog crunch": "crunch grenouille",
        "frog planche": "planche grenouille",
        "front lever": "front lever",
        "front lever reps": "front lever répétitions",
        "front plank with twist": "plank avant avec rotation",
        "full maltese": "maltese complet",
        "full planche": "planche complète",
        "full planche push-up": "pompe planche complète",
        "gironda sternum chin": "traction sternale Gironda",
        "glute bridge march": "pont fessier marche",
        "glute bridge two legs on bench (male)": "pont fessier deux jambes sur banc",
        "glute-ham raise": "relevé fessier-ischio",
        "gorilla chin": "traction gorille",
        "groin crunch": "crunch aine",
        "hack calf raise": "élévation mollets hack",
        "hack one leg calf raise": "élévation mollet unipodal hack",
        "half knee bends (male)": "demi-flexions des genoux",
        "half sit-up (male)": "demi-crunch assis",
        "hamstring stretch": "étirement ischio-jambiers",
        "hands bike": "vélo à mains",
        "hands clasped circular toe touch (male)": "toucher circulaire des orteils mains jointes",
        "hands reversed clasped circular toe touch (male)": "toucher circulaire inversé des orteils mains jointes",
        "handstand": "poirier",
        "handstand push-up": "pompe en poirier",
        "hanging leg hip raise": "relevé hanche jambes suspendues",
        "hanging leg raise": "relevé de jambes suspendu",
        "hanging oblique knee raise": "relevé oblique des genoux suspendu",
        "hanging pike": "pique suspendu",
        "hanging straight leg hip raise": "relevé hanche jambes tendues suspendu",
        "hanging straight leg raise": "relevé jambes tendues suspendu",
        "hanging straight twisting leg hip raise": "relevé hanche rotation jambes tendues suspendu",
        "high knee against wall": "genou haut contre le mur",
        "hip raise (bent knee)": "levée de hanche genoux fléchis",
        "hug keens to chest": "genoux contre la poitrine",
        "hyght dumbbell fly": "écarté haltères large amplitude",
        "hyperextension": "hyperextension",
        "hyperextension (on bench)": "hyperextension (sur banc)",
        "impossible dips": "dips impossibles",
        "inchworm": "chenille",
        "inchworm v. 2": "chenille v. 2",
        "incline close-grip push-up": "pompe inclinée prise serrée",
        "incline leg hip raise (leg straight)": "relevé hanche incliné jambe tendue",
        "incline push up depth jump": "pompe inclinée saut de profondeur",
        "incline push-up": "pompe inclinée",
        "incline push-up (on box)": "pompe inclinée sur boîte",
        "incline reverse grip push-up": "pompe inclinée prise inversée",
        "incline scapula push up": "pompe scapulaire inclinée",
        "incline twisting sit-up": "crunch assis incliné twisté",
        "intermediate hip flexor and quad stretch": "étirement fléchisseur de hanche et quadriceps intermédiaire",
        "inverse leg curl (bench support)": "curl jambes inversé (appui banc)",
        "inverse leg curl (on pull-up cable machine)": "curl jambes inversé (machine traction poulie)",
        "inverted row": "rowing inversé",
        "inverted row bent knees": "rowing inversé genoux fléchis",
        "inverted row on bench": "rowing inversé sur banc",
        "inverted row v. 2": "rowing inversé v. 2",
        "inverted row with straps": "rowing inversé avec sangles",
        "iron cross stretch": "étirement croix de fer",
        "isometric chest squeeze": "squeeze pectoraux isométrique",
        "isometric wipers": "essuie-glaces isométrique",
        "jack burpee": "burpee jumping jack",
        "jack jump (male)": "jumping jack",
        "jackknife sit-up": "crunch jackknife",
        "janda sit-up": "crunch Janda",
        "jump rope": "corde à sauter",
        "jump squat": "squat sauté",
        "jump squat v. 2": "squat sauté v. 2",
        "kettlebell advanced windmill": "windmill avancé kettlebell",
        "kettlebell alternating hang clean": "épaulé suspendu alterné kettlebell",
        "kettlebell alternating press": "développé alterné kettlebell",
        "kettlebell alternating press on floor": "développé alterné au sol kettlebell",
        "kettlebell alternating renegade row": "rowing renégat alterné kettlebell",
        "kettlebell alternating row": "rowing alterné kettlebell",
        "kettlebell arnold press": "développé Arnold kettlebell",
        "kettlebell bent press": "développé penché kettlebell",
        "kettlebell bottoms up clean from the hang position": "épaulé fond en haut en suspension kettlebell",
        "kettlebell double alternating hang clean": "épaulé suspendu double alterné kettlebell",
        "kettlebell double jerk": "jeté double kettlebell",
        "kettlebell double push press": "push press double kettlebell",
        "kettlebell double snatch": "arraché double kettlebell",
        "kettlebell double windmill": "windmill double kettlebell",
        "kettlebell extended range one arm press on floor": "développé un bras pleine amplitude au sol kettlebell",
        "kettlebell figure 8": "figure en huit kettlebell",
        "kettlebell front squat": "squat avant kettlebell",
        "kettlebell goblet squat": "goblet squat kettlebell",
        "kettlebell hang clean": "épaulé suspendu kettlebell",
        "kettlebell lunge pass through": "fente avec passage kettlebell",
        "kettlebell one arm clean and jerk": "épaulé-jeté un bras kettlebell",
        "kettlebell one arm floor press": "développé au sol un bras kettlebell",
        "kettlebell one arm jerk": "jeté un bras kettlebell",
        "kettlebell one arm military press to the side": "développé militaire latéral un bras kettlebell",
        "kettlebell one arm push press": "push press un bras kettlebell",
        "kettlebell one arm row": "rowing un bras kettlebell",
        "kettlebell one arm snatch": "arraché un bras kettlebell",
        "kettlebell pirate supper legs": "squats pirates kettlebell",
        "kettlebell pistol squat": "squat pistolet kettlebell",
        "kettlebell plyo push-up": "pompe pliométrique kettlebell",
        "kettlebell seated press": "développé assis kettlebell",
        "kettlebell seated two arm military press": "développé militaire deux bras assis kettlebell",
        "kettlebell seesaw press": "développé balançoire kettlebell",
        "kettlebell sumo high pull": "tirage haut sumo kettlebell",
        "kettlebell swing": "swing kettlebell",
        "kettlebell thruster": "thruster kettlebell",
        "kettlebell turkish get up (squat style)": "Turkish get-up style squat kettlebell",
        "kettlebell two arm clean": "épaulé deux bras kettlebell",
        "kettlebell two arm military press": "développé militaire deux bras kettlebell",
        "kettlebell two arm row": "rowing deux bras kettlebell",
        "kettlebell windmill": "windmill kettlebell",
        "kick out sit": "sit kick-out",
        "kipping muscle up": "muscle-up kipping",
        "knee touch crunch": "crunch toucher des genoux",
        "kneeling jump squat": "squat sauté agenouillé",
        "kneeling lat stretch": "étirement dorsal agenouillé",
        "kneeling plank tap shoulder (male)": "plank agenouillé tape épaule",
        "kneeling push-up (male)": "pompe agenouillée",
        "korean dips": "dips coréens",
        "l-pull-up": "traction en L",
        "l-sit on floor": "L-sit au sol",
        "landmine 180": "landmine 180°",
        "landmine lateral raise": "élévation latérale landmine",
        "lean planche": "planche penchée",
        "left hook. boxing": "crochet gauche boxe",
        "leg pull in flat bench": "relevé de jambes banc plat",
        "leg up hamstring stretch": "étirement ischio-jambiers jambe levée",
        "lever alternate leg press": "presse à jambes alternée machine",
        "lever alternating narrow grip seated row": "rowing assis prise étroite alternée machine",
        "lever assisted chin-up": "traction sous-main assistée machine",
        "lever back extension": "extension dorsale machine",
        "lever bent over row": "rowing penché machine",
        "lever bent-over row with v-bar": "rowing penché barre V machine",
        "lever bicep curl": "curl biceps machine",
        "lever calf press": "presse mollets machine",
        "lever chest press": "développé pectoraux machine",
        "lever deadlift": "soulevé de terre machine",
        "lever decline chest press": "développé décliné machine",
        "lever donkey calf raise": "élévation mollets âne machine",
        "lever front pulldown": "tirage avant machine",
        "lever gripless shrug": "haussement d'épaules sans prise machine",
        "lever gripless shrug v. 2": "haussement d'épaules sans prise machine v. 2",
        "lever gripper hands": "renforcement des mains machine",
        "lever hammer grip preacher curl": "curl pupitre prise marteau machine",
        "lever high row": "rowing haut machine",
        "lever hip extension v. 2": "extension de hanche machine v. 2",
        "lever horizontal one leg press": "presse horizontale unipodal machine",
        "lever incline chest press": "développé incliné machine",
        "lever incline chest press v. 2": "développé incliné machine v. 2",
        "lever kneeling leg curl": "curl jambes agenouillé machine",
        "lever kneeling twist": "rotation agenouillée machine",
        "lever lateral raise": "élévation latérale machine",
        "lever leg extension": "extension des jambes machine",
        "lever lying leg curl": "curl jambes allongé machine",
        "lever lying two-one leg curl": "curl jambes allongé 2-1 machine",
        "lever military press": "développé militaire machine",
        "lever narrow grip seated row": "rowing assis prise étroite machine",
        "lever one arm bent over row": "rowing penché un bras machine",
        "lever one arm lateral high row": "rowing latéral haut un bras machine",
        "lever one arm lateral wide pulldown": "tirage latéral large un bras machine",
        "lever one arm shoulder press": "développé épaules un bras machine",
        "lever overhand triceps dip": "dips triceps sur-main machine",
        "lever preacher curl": "curl pupitre machine",
        "lever preacher curl v. 2": "curl pupitre machine v. 2",
        "lever pullover": "pullover machine",
        "lever reverse grip lateral pulldown": "tirage latéral prise inversée machine",
        "lever reverse grip preacher curl": "curl pupitre prise inversée machine",
        "lever reverse grip vertical row": "rowing vertical prise inversée machine",
        "lever reverse hyperextension": "hyperextension inversée machine",
        "lever reverse t-bar row": "rowing barre en T inversé machine",
        "lever rotary calf": "rotation mollet machine",
        "lever seated calf press": "presse mollets assis machine",
        "lever seated calf raise": "élévation des mollets assis machine",
        "lever seated crunch": "crunch assis machine",
        "lever seated crunch (chest pad)": "crunch assis machine (coussin pectoraux)",
        "lever seated crunch v. 2": "crunch assis machine v. 2",
        "lever seated dip": "dips assis machine",
        "lever seated fly": "écarté assis machine",
        "lever seated good morning": "good morning assis machine",
        "lever seated hip abduction": "abduction de hanche assise machine",
        "lever seated hip adduction": "adduction de hanche assise machine",
        "lever seated leg curl": "curl jambes assis machine",
        "lever seated leg raise crunch": "crunch relevé de jambes assis machine",
        "lever seated reverse fly": "écarté inversé assis machine",
        "lever seated reverse fly (parallel grip)": "écarté inversé assis prise parallèle machine",
        "lever seated row": "rowing assis machine",
        "lever seated squat calf raise on leg press machine": "élévation mollets squat assis sur presse machine",
        "lever shoulder press": "développé épaules machine",
        "lever shoulder press v. 2": "développé épaules machine v. 2",
        "lever shoulder press v. 3": "développé épaules machine v. 3",
        "lever shrug": "haussement d'épaules machine",
        "lever standing calf raise": "élévation des mollets debout machine",
        "lever standing chest press": "développé pectoraux debout machine",
        "lever t bar row": "rowing barre en T machine",
        "lever t-bar reverse grip row": "rowing barre en T prise inversée machine",
        "lever triceps extension": "extension triceps machine",
        "lever unilateral row": "rowing unilatéral machine",
        "london bridge": "pont de Londres",
        "low glute bridge on floor": "pont fessier bas au sol",
        "lower back curl": "curl bas du dos",
        "lunge with jump": "fente sautée",
        "lunge with twist": "fente avec rotation",
        "lying (side) quads stretch": "étirement quadriceps allongé sur le côté",
        "lying elbow to knee": "coude au genou allongé",
        "lying leg raise flat bench": "élévation de jambes allongée banc plat",
        "lying leg-hip raise": "relevé hanche-jambes allongé",
        "machine inner chest press": "développé pectoraux intérieur machine",
        "march sit (wall)": "march assis contre le mur",
        "medicine ball catch and overhead throw": "attraper et lancer au-dessus ballon médicinal",
        "medicine ball chest pass": "passe poitrine ballon médicinal",
        "medicine ball chest push from 3 point stance": "poussée pectoraux 3 appuis ballon médicinal",
        "medicine ball chest push multiple response": "poussée pectoraux multi-répétitions ballon médicinal",
        "medicine ball chest push single response": "poussée pectoraux une répétition ballon médicinal",
        "medicine ball chest push with run release": "poussée pectoraux avec course ballon médicinal",
        "medicine ball close grip push up": "pompe prise serrée ballon médicinal",
        "medicine ball overhead slam": "slam au-dessus ballon médicinal",
        "medicine ball supine chest throw": "lancer pectoraux couché ballon médicinal",
        "mixed grip chin-up": "traction prise mixte",
        "modified hindu push-up (male)": "pompe hindoue modifiée",
        "modified push up to lower arms": "pompe modifiée avec abaissement des bras",
        "monster walk": "marche monstre",
        "mountain climber": "grimpeur",
        "muscle up": "muscle-up",
        "muscle-up (on vertical bar)": "muscle-up (sur barre verticale)",
        "narrow push-up on exercise ball": "pompe prise étroite sur ballon",
        "neck side stretch": "étirement latéral du cou",
        "negative crunch": "crunch négatif",
        "oblique crunch v. 2": "crunch oblique v. 2",
        "oblique crunches floor": "crunch oblique au sol",
        "olympic barbell hammer curl": "curl marteau barre olympique",
        "olympic barbell triceps extension": "extension triceps barre olympique",
        "one arm against wall": "un bras contre le mur",
        "one arm chin-up": "traction sous-main un bras",
        "one arm dip": "dips un bras",
        "one arm slam (with medicine ball)": "slam un bras (ballon médicinal)",
        "one arm towel row": "rowing serviette un bras",
        "one leg donkey calf raise": "élévation mollet âne unipodal",
        "one leg floor calf raise": "élévation mollet au sol unipodal",
        "one leg squat": "squat unipodal",
        "otis up": "Otis up",
        "outside leg kick push-up": "pompe avec coup de pied latéral",
        "overhead triceps stretch": "étirement triceps au-dessus de la tête",
        "pelvic tilt": "bascule du bassin",
        "pelvic tilt into bridge": "bascule du bassin en pont",
        "peroneals stretch": "étirement péroniers",
        "pike-to-cobra push-up": "pompe pique vers cobra",
        "plyo push up": "pompe pliométrique",
        "posterior step to overhead reach": "pas arrière avec élévation au-dessus",
        "posterior tibialis stretch": "étirement tibial postérieur",
        "potty squat": "squat toilettes",
        "potty squat with support": "squat toilettes avec appui",
        "power clean": "épaulé puissance",
        "power point plank": "plank point de puissance",
        "prisoner half sit-up (male)": "demi-crunch prisonnier",
        "prone twist on stability ball": "rotation couché face sur ballon de stabilité",
        "pull up (neutral grip)": "traction prise neutre",
        "pull-in (on stability ball)": "relevé sur ballon de stabilité",
        "pull-up": "traction",
        "push and pull bodyweight": "poussée et tirage au poids du corps",
        "push to run": "poussée vers la course",
        "push up on bosu ball": "pompe sur bosu",
        "push-up": "pompe",
        "push-up (bosu ball)": "pompe sur bosu",
        "push-up (on stability ball)": "pompe sur ballon de stabilité",
        "push-up (wall)": "pompe contre le mur",
        "push-up (wall) v. 2": "pompe contre le mur v. 2",
        "push-up close-grip off dumbbell": "pompe prise serrée sur haltère",
        "push-up inside leg kick": "pompe avec coup de genou",
        "push-up medicine ball": "pompe sur ballon médicinal",
        "push-up on lower arms": "pompe sur avant-bras",
        "push-up plus": "pompe plus",
        "push-up to side plank": "pompe vers plank latéral",
        "quads": "quadriceps",
        "quarter sit-up": "quart de crunch assis",
        "quick feet v. 2": "pieds rapides v. 2",
        "raise single arm push-up": "pompe élévation un bras",
        "rear decline bridge": "pont décliné arrière",
        "rear deltoid stretch": "étirement deltoïde postérieur",
        "rear pull-up": "traction arrière",
        "reclining big toe pose with rope": "posture orteil allongé avec corde",
        "resistance band hip thrusts on knees (female)": "poussée de hanches agenouillé élastique de résistance",
        "resistance band leg extension": "extension des jambes élastique de résistance",
        "resistance band seated biceps curl": "curl biceps assis élastique de résistance",
        "resistance band seated chest press": "développé pectoraux assis élastique de résistance",
        "resistance band seated hip abduction": "abduction de hanche assise élastique de résistance",
        "resistance band seated shoulder press": "développé épaules assis élastique de résistance",
        "resistance band seated straight back row": "rowing assis dos droit élastique de résistance",
        "reverse crunch": "crunch inversé",
        "reverse dip": "dips inversé",
        "reverse grip machine lat pulldown": "tirage dorsaux prise inversée machine",
        "reverse grip pull-up": "traction prise inversée",
        "reverse hyper extension (on stability ball)": "hyperextension inversée sur ballon de stabilité",
        "reverse hyper on flat bench": "hyperextension inversée sur banc plat",
        "reverse plank with leg lift": "plank inversé avec élévation de jambe",
        "ring dips": "dips aux anneaux",
        "rocking frog stretch": "étirement grenouille en balancement",
        "rocky pull-up pulldown": "traction-tirage Rocky",
        "roller back stretch": "étirement dorsal au rouleau",
        "roller body saw": "scie corporelle au rouleau",
        "roller hip lat stretch": "étirement hanche-dorsal au rouleau",
        "roller hip stretch": "étirement hanche au rouleau",
        "roller reverse crunch": "crunch inversé au rouleau",
        "roller seated shoulder flexor depresor retractor": "fléchisseur-dépresseur-rétracteur épaule assis au rouleau",
        "roller seated single leg shoulder flexor depresor retractor": "fléchisseur-dépresseur-rétracteur épaule unipodal assis au rouleau",
        "roller side lat stretch": "étirement dorsal latéral au rouleau",
        "rope climb": "grimper à la corde",
        "run": "course",
        "run (equipment)": "course (équipement)",
        "runners stretch": "étirement du coureur",
        "russian twist": "rotation russe",
        "scapula dips": "dips scapulaires",
        "scapula push-up": "pompe scapulaire",
        "scapular pull-up": "traction scapulaire",
        "scissor jumps (male)": "sauts ciseaux",
        "seated calf stretch (male)": "étirement mollets assis",
        "seated glute stretch": "étirement fessiers assis",
        "seated leg raise": "élévation de jambes assis",
        "seated lower back stretch": "étirement bas du dos assis",
        "seated piriformis stretch": "étirement piriforme assis",
        "seated side crunch (wall)": "crunch latéral assis contre le mur",
        "seated wide angle pose sequence": "séquence posture angle large assis",
        "self assisted inverse leg curl": "curl jambes inversé auto-assisté",
        "self assisted inverse leg curl (on floor)": "curl jambes inversé auto-assisté au sol",
        "semi squat jump (male)": "demi-squat sauté",
        "short stride run": "course à foulées courtes",
        "shoulder grip pull-up": "traction prise épaules",
        "shoulder tap": "tape sur épaule",
        "shoulder tap push-up": "pompe avec tape sur épaule",
        "side bridge hip abduction": "abduction de hanche pont latéral",
        "side bridge v. 2": "pont latéral v. 2",
        "side hip (on parallel bars)": "hanche latérale (barres parallèles)",
        "side hip abduction": "abduction de hanche latérale",
        "side lying floor stretch": "étirement allongé sur le côté au sol",
        "side lying hip adduction (male)": "adduction de hanche allongée sur le côté",
        "side plank hip adduction": "adduction de hanche en plank latéral",
        "side push neck stretch": "étirement latéral du cou poussée",
        "side push-up": "pompe latérale",
        "side wrist pull stretch": "étirement tirage poignet latéral",
        "side-to-side chin": "traction côté à côté",
        "side-to-side toe touch (male)": "toucher des orteils côté à côté",
        "single arm push-up": "pompe un bras",
        "single leg bridge with outstretched leg": "pont unipodal jambe tendue",
        "single leg calf raise (on a dumbbell)": "élévation mollet unipodal sur haltère",
        "single leg platform slide": "glissade unipodal sur plateforme",
        "single leg squat (pistol) male": "squat pistolet unipodal",
        "sissy squat": "sissy squat",
        "sit-up v. 2": "crunch assis v. 2",
        "sit-up with arms on chest": "crunch assis bras croisés sur la poitrine",
        "skater hops": "sauts de patineur",
        "ski ergometer": "ergomètre ski",
        "ski step": "pas de ski",
        "skin the cat": "skin the cat (anneaux)",
        "sled 45 degrees one leg press": "presse une jambe 45° traîneau",
        "sled 45° leg press (side pov)": "presse jambes 45° traîneau (vue côté)",
        "sled 45в° calf press": "presse mollets 45° traîneau",
        "sled 45в° leg press": "presse jambes 45° traîneau",
        "sled 45в° leg press (back pov)": "presse jambes 45° traîneau (vue arrière)",
        "sled 45в° leg wide press": "presse jambes large 45° traîneau",
        "sled calf press on leg press": "presse mollets sur presse jambes",
        "sled closer hack squat": "hack squat serré traîneau",
        "sled forward angled calf raise": "élévation mollets incliné avant traîneau",
        "sled hack squat": "hack squat traîneau",
        "sled lying calf press": "presse mollets allongée traîneau",
        "sled lying squat": "squat allongé traîneau",
        "sled one leg calf press on leg press": "presse mollets unipodal sur presse jambes",
        "sledge hammer": "marteau de forge",
        "smith back shrug": "haussement d'épaules arrière guidon Smith",
        "smith behind neck press": "développé nuque guidon Smith",
        "smith bench press": "développé couché guidon Smith",
        "smith bent knee good morning": "good morning genoux fléchis guidon Smith",
        "smith bent over row": "rowing penché guidon Smith",
        "smith chair squat": "squat chaise guidon Smith",
        "smith close-grip bench press": "développé couché prise serrée guidon Smith",
        "smith deadlift": "soulevé de terre guidon Smith",
        "smith decline bench press": "développé couché décliné guidon Smith",
        "smith decline reverse-grip press": "développé décliné prise inversée guidon Smith",
        "smith front squat (clean grip)": "squat avant prise épaulé guidon Smith",
        "smith full squat": "squat complet guidon Smith",
        "smith hack squat": "hack squat guidon Smith",
        "smith hip raise": "levée de hanche guidon Smith",
        "smith incline bench press": "développé couché incliné guidon Smith",
        "smith incline reverse-grip press": "développé incliné prise inversée guidon Smith",
        "smith incline shoulder raises": "élévations épaules inclinées guidon Smith",
        "smith leg press": "presse à jambes guidon Smith",
        "smith low bar squat": "squat barre basse guidon Smith",
        "smith machine bicep curl": "curl biceps guidon Smith",
        "smith machine decline close grip bench press": "développé couché décliné prise serrée guidon Smith",
        "smith machine incline tricep extension": "extension triceps inclinée guidon Smith",
        "smith machine reverse decline close grip bench press": "développé décliné inversé prise serrée guidon Smith",
        "smith narrow row": "rowing prise étroite guidon Smith",
        "smith one arm row": "rowing un bras guidon Smith",
        "smith one leg floor calf raise": "élévation mollet unipodal au sol guidon Smith",
        "smith rear delt row": "rowing delta postérieur guidon Smith",
        "smith reverse calf raises": "élévation mollets inversée guidon Smith",
        "smith reverse grip bent over row": "rowing penché prise inversée guidon Smith",
        "smith reverse-grip press": "développé prise inversée guidon Smith",
        "smith seated one leg calf raise": "élévation mollet unipodal assis guidon Smith",
        "smith seated shoulder press": "développé épaules assis guidon Smith",
        "smith seated wrist curl": "curl poignet assis guidon Smith",
        "smith shoulder press": "développé épaules guidon Smith",
        "smith shrug": "haussement d'épaules guidon Smith",
        "smith single leg split squat": "squat fendu unipodal guidon Smith",
        "smith sprint lunge": "fente sprint guidon Smith",
        "smith squat": "squat guidon Smith",
        "smith standing back wrist curl": "curl poignet dorsal debout guidon Smith",
        "smith standing behind head military press": "développé militaire derrière la tête debout guidon Smith",
        "smith standing leg calf raise": "élévation mollet unipodal debout guidon Smith",
        "smith standing military press": "développé militaire debout guidon Smith",
        "smith sumo squat": "squat sumo guidon Smith",
        "smith toe raise": "élévation pointe de pieds guidon Smith",
        "smith upright row": "tirage vertical guidon Smith",
        "smith wide grip bench press": "développé couché prise large guidon Smith",
        "smith wide grip decline bench press": "développé couché décliné prise large guidon Smith",
        "snatch pull": "tirage arraché",
        "spell caster": "lanceur de sorts",
        "sphinx": "sphinx",
        "spider crawl push up": "pompe araignée rampante",
        "spine stretch": "étirement de la colonne",
        "spine twist": "rotation de la colonne",
        "split squats": "squats fendus",
        "squat jerk": "squat-jeté",
        "squat on bosu ball": "squat sur bosu",
        "squat to overhead reach": "squat vers élévation au-dessus",
        "squat to overhead reach with twist": "squat vers élévation au-dessus avec rotation",
        "stability ball crunch (full range hands behind head)": "crunch ballon de stabilité pleine amplitude mains derrière la tête",
        "stalder press": "développé Stalder",
        "standing archer": "archer debout",
        "standing behind neck press": "développé militaire derrière la nuque debout",
        "standing calf raise (on a staircase)": "élévation des mollets debout (sur escalier)",
        "standing calves": "mollets debout",
        "standing calves calf stretch": "étirement mollets debout",
        "standing hamstring and calf stretch with strap": "étirement ischio-jambiers et mollets debout avec sangle",
        "standing lateral stretch": "étirement latéral debout",
        "standing pelvic tilt": "bascule du bassin debout",
        "standing single leg curl": "curl jambe unipodal debout",
        "standing wheel rollerout": "roue debout",
        "star jump (male)": "saut étoile",
        "stationary bike run v. 3": "vélo stationnaire course v. 3",
        "stationary bike walk": "vélo stationnaire marche",
        "straddle maltese": "maltese en écart",
        "straddle planche": "planche en écart",
        "straight leg outer hip abductor": "abducteur externe hanche jambe tendue",
        "superman push-up": "pompe superman",
        "suspended abdominal fallout": "gainage en suspension abdominaux",
        "suspended push-up": "pompe en suspension",
        "suspended reverse crunch": "crunch inversé en suspension",
        "suspended row": "rowing en suspension",
        "suspended split squat": "squat fendu en suspension",
        "swimmer kicks v. 2 (male)": "battements nageur v. 2",
        "swing 360": "swing 360°",
        "three bench dip": "dips trois bancs",
        "tire flip": "retournement de pneu",
        "triceps dip": "dips triceps",
        "triceps dip (bench leg)": "dips triceps (jambe sur banc)",
        "triceps dip (between benches)": "dips triceps (entre bancs)",
        "triceps dips floor": "dips triceps au sol",
        "triceps press": "développé triceps",
        "triceps stretch": "étirement triceps",
        "tuck crunch": "crunch ramassé",
        "twin handle parallel grip lat pulldown": "tirage dorsaux prise parallèle double poignée",
        "twist hip lift": "levée de hanche twistée",
        "twisted leg raise": "élévation de jambes twistée",
        "twisted leg raise (female)": "élévation de jambes twistée",
        "two toe touch (male)": "toucher des deux orteils",
        "upper back stretch": "étirement haut du dos",
        "upward facing dog": "chien regardant vers le haut",
        "v-sit on floor": "V-sit au sol",
        "vertical leg raise (on parallel bars)": "élévation de jambes verticale aux barres parallèles",
        "walk elliptical cross trainer": "marche elliptique",
        "walking high knees lunge": "fente marche genoux hauts",
        "walking lunge": "fente en marche",
        "walking on incline treadmill": "marche sur tapis incliné",
        "walking on stepmill": "marche sur stepper",
        "weighted bench dip": "dips sur banc lesté",
        "weighted close grip chin-up on dip cage": "traction prise serrée lestée sur cage",
        "weighted cossack squats (male)": "squats cosaques lestés",
        "weighted crunch": "crunch lesté",
        "weighted decline sit-up": "crunch assis décliné lesté",
        "weighted donkey calf raise": "élévation mollets âne lestée",
        "weighted drop push up": "pompe à lâcher lestée",
        "weighted front plank": "plank avant lesté",
        "weighted front raise": "élévation frontale lestée",
        "weighted hanging leg-hip raise": "relevé hanche-jambes suspendu lesté",
        "weighted hyperextension (on stability ball)": "hyperextension lestée sur ballon de stabilité",
        "weighted kneeling step with swing": "pas agenouillé avec balancement lesté",
        "weighted lunge with swing": "fente avec balancement lestée",
        "weighted muscle up": "muscle-up lesté",
        "weighted muscle up (on bar)": "muscle-up lesté (sur barre)",
        "weighted one hand pull up": "traction un bras lestée",
        "weighted overhead crunch (on stability ball)": "crunch au-dessus lesté sur ballon de stabilité",
        "weighted pull-up": "traction lestée",
        "weighted round arm": "rotation circulaire bras lestée",
        "weighted russian twist": "rotation russe lestée",
        "weighted russian twist (legs up)": "rotation russe lestée jambes levées",
        "weighted russian twist v. 2": "rotation russe lestée v. 2",
        "weighted seated bicep curl (on stability ball)": "curl biceps assis lesté sur ballon de stabilité",
        "weighted seated twist (on stability ball)": "rotation assise lestée sur ballon de stabilité",
        "weighted side bend (on stability ball)": "inclinaison latérale lestée sur ballon de stabilité",
        "weighted sissy squat": "sissy squat lesté",
        "weighted squat": "squat lesté",
        "weighted standing curl": "curl debout lesté",
        "weighted standing hand squeeze": "pression des mains debout lestée",
        "weighted straight bar dip": "dips barre droite lesté",
        "weighted stretch lunge": "fente étirement lestée",
        "weighted svend press": "développé Svend lesté",
        "weighted three bench dips": "dips trois bancs lesté",
        "weighted tricep dips": "dips triceps lestés",
        "weighted triceps dip on high parallel bars": "dips triceps hautes barres parallèles lesté",
        "wheel rollerout": "roue (rollout)",
        "wheel run": "course à la roue",
        "wide grip pull-up": "traction prise large",
        "wide grip rear pull-up": "traction arrière prise large",
        "wide hand push up": "pompe prise large",
        "wide-grip chest dip on high parallel bars": "dips pectoraux prise large hautes barres parallèles",
        "wind sprints": "sprints vent",
        "world greatest stretch": "le grand étirement mondial",
        "wrist circles": "cercles de poignet",
        "wrist rollerer": "rouleau de poignet",
    }

    if n in exact:
        return exact[n]

    # Fallback: partial translations
    result = n

    replacements = [
        ("smith machine", "guidon Smith"),
        ("bench press", "développé couché"),
        ("pull-up", "traction"),
        ("pull up", "traction"),
        ("push-up", "pompe"),
        ("push up", "pompe"),
        ("lat pull-down", "tirage dorsaux"),
        ("lat pulldown", "tirage dorsaux"),
        ("face pull", "tirage face à face"),
        ("hip thrust", "poussée de hanches"),
        ("glute bridge", "pont fessier"),
        ("leg curl", "curl jambes"),
        ("leg press", "presse à jambes"),
        ("leg extension", "extension des jambes"),
        ("calf raise", "élévation des mollets"),
        ("front raise", "élévation frontale"),
        ("lateral raise", "élévation latérale"),
        ("rear delt", "delta postérieur"),
        ("hip abduction", "abduction de hanche"),
        ("hip adduction", "adduction de hanche"),
        ("upright row", "tirage vertical"),
        ("preacher curl", "curl pupitre"),
        ("hammer curl", "curl marteau"),
        ("goblet squat", "goblet squat"),
        ("split squat", "squat fendu"),
        ("pistol squat", "squat pistolet"),
        ("sumo squat", "squat sumo"),
        ("hack squat", "hack squat"),
        ("front squat", "squat avant"),
        ("jump squat", "squat sauté"),
        ("turkish get-up", "Turkish get-up"),
        ("good morning", "good morning"),
        ("deadlift", "soulevé de terre"),
        ("barbell", "barre"),
        ("dumbbell", "haltères"),
        ("kettlebell", "kettlebell"),
        ("machine", "machine"),
        ("cable", "poulie"),
        ("squat", "squat"),
        ("lunge", "fente"),
        ("curl", "curl"),
        ("press", "développé"),
        ("row", "rowing"),
        ("raise", "élévation"),
        ("extension", "extension"),
        ("crunch", "crunch"),
        ("plank", "plank"),
        ("dip", "dips"),
        ("pullover", "pullover"),
        ("skullcrusher", "brise-crâne"),
        ("burpee", "burpee"),
        ("thruster", "thruster"),
        ("snatch", "arraché"),
        ("clean", "épaulé"),
        ("jerk", "jeté"),
        ("shrug", "haussement d'épaules"),
        ("twist", "rotation"),
        ("stretch", "étirement"),
        ("swing", "swing"),
        ("jump", "saut"),
        ("run", "course"),
        ("incline", "incliné"),
        ("decline", "décliné"),
        ("seated", "assis"),
        ("standing", "debout"),
        ("lying", "allongé"),
        ("overhead", "au-dessus de la tête"),
        ("assisted", "assisté"),
        ("weighted", "lesté"),
        ("reverse", "inversé"),
        ("alternating", "alterné"),
        ("alternate", "alterné"),
        ("single", "unilatéral"),
        ("neutral", "neutre"),
        ("wide grip", "prise large"),
        ("close grip", "prise serrée"),
        ("wide-grip", "prise large"),
        ("close-grip", "prise serrée"),
        ("parallel", "parallèle"),
        ("straight", "droit"),
        ("bent", "fléchi"),
        ("kneeling", "agenouillé"),
        ("inverted", "inversé"),
        ("hanging", "suspendu"),
        ("sumo", "sumo"),
        ("romanian", "roumain"),
        ("bulgarian", "bulgare"),
    ]

    for eng, fr in replacements:
        result = result.replace(eng, fr)

    return result


def sql_escape(s):
    return s.replace("'", "''")


lines = []
lines.append("UPDATE public.exercises SET name_fr = CASE id")
for ex in exercises:
    fr = translate(ex['name'])
    lines.append(f"  WHEN '{ex['id']}' THEN '{sql_escape(fr)}'")
lines.append("  ELSE name_fr")
lines.append("END")
ids = ", ".join(f"'{ex['id']}'" for ex in exercises)
lines.append(f"WHERE id IN ({ids});")

with open('C:/ziko-platform/supabase/migrations/022_exercises_name_fr.sql', 'w', encoding='utf-8') as out:
    out.write('\n'.join(lines))

print(f"Written {len(exercises)} exercises")
