-- Phase 2 (supabase-portfolio-migration): ziko functions/triggers -> ziko_-prefixed objects.
-- GENERATED by scripts/portfolio-migration/02-dump-and-rewrite.js. Do not hand-edit.
-- Requires the companion *_portfolio_ziko_schema.sql migration to be applied first.
-- Intentionally NOT included (D-02): CREATE TRIGGER on_auth_user_created / on_auth_user_created_credits
--   on auth.users -- Phase 3 attaches them to ziko_handle_new_user() / ziko_handle_new_user_credits().
-- Intentionally NOT included: event trigger ensure_rls (ziko_rls_auto_enable() is created, not attached);
--   an event trigger is database-wide and would alter behaviour for the rh_*/gecko_* tenants.
-- ACTION REQUIRED BEFORE APPLY: the two push triggers carry the placeholder {{X_WEBHOOK_SECRET}} in their
--   X-Webhook-Secret header. Substitute the real secret at apply time (Plan 05/07); never commit it.

-- Extensions required by the ziko functions/triggers (evidence: rename-map.generated.json required_extensions).
CREATE EXTENSION IF NOT EXISTS pg_net;
CREATE EXTENSION IF NOT EXISTS unaccent;

-- SQL-language function bodies are validated at creation; keep creation order-independent.
SET check_function_bodies = off;

-- ── Functions ──────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.ziko_anonymize_waitlist_signup(p_email text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_normalized TEXT := public.ziko_normalize_waitlist_email(p_email);
  v_updated    INTEGER;
BEGIN
  UPDATE public.ziko_waitlist_signups
  SET email            = 'anonymized+' || id::text || '@erased.invalid',
      email_normalized = 'anonymized-' || id::text,
      utm_source       = NULL,
      utm_campaign     = NULL,
      anonymized_at    = NOW()
  WHERE email_normalized = v_normalized AND anonymized_at IS NULL;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated > 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_award_coins(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  PERFORM public.ziko_ensure_gamification_profile(p_user_id);

  INSERT INTO public.ziko_coin_transactions (user_id, amount, source, source_id, description)
  VALUES (p_user_id, p_amount, p_source, p_source_id, p_description);

  -- Atomic increment — no read-then-write race
  UPDATE public.ziko_user_gamification
  SET coins = coins + p_amount, updated_at = NOW()
  WHERE user_id = p_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_award_xp(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_profile      public.ziko_user_gamification;
  v_new_xp       INTEGER;
  v_new_level    INTEGER;
  v_leveled_up   BOOLEAN;
  v_level_title  TEXT;
  v_reward_coins INTEGER;
BEGIN
  v_profile := public.ziko_ensure_gamification_profile(p_user_id);

  INSERT INTO public.ziko_xp_transactions (user_id, amount, source, source_id, description)
  VALUES (p_user_id, p_amount, p_source, p_source_id, p_description);

  v_new_xp := v_profile.xp + p_amount;

  SELECT level INTO v_new_level
  FROM public.ziko_level_definitions
  WHERE xp_required <= v_new_xp
  ORDER BY level DESC
  LIMIT 1;

  v_new_level := COALESCE(v_new_level, v_profile.level);
  v_leveled_up := v_new_level > v_profile.level;

  UPDATE public.ziko_user_gamification
  SET xp = v_new_xp, level = v_new_level, updated_at = NOW()
  WHERE user_id = p_user_id;

  IF v_leveled_up THEN
    SELECT reward_coins, title INTO v_reward_coins, v_level_title
    FROM public.ziko_level_definitions WHERE level = v_new_level;

    IF v_reward_coins > 0 THEN
      PERFORM public.ziko_award_coins(
        p_user_id, v_reward_coins, 'level_up', NULL,
        format('🎉 Niveau %s atteint : %s !', v_new_level, v_level_title)
      );
    END IF;
  END IF;

  RETURN jsonb_build_object('leveled_up', v_leveled_up, 'new_level', v_new_level);
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_check_and_award_badges(p_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
DECLARE
  v_sessions      INTEGER := 0;
  v_streak        INTEGER := 0;
  v_prs           INTEGER := 0;
  v_friends       INTEGER := 0;
  v_profile_done  INTEGER := 0;
  v_streak_date   DATE;
  v_consecutive   INTEGER;
  rec             RECORD;
BEGIN
  SELECT COUNT(*) INTO v_sessions
  FROM public.ziko_workout_sessions
  WHERE user_id = p_user_id;

  BEGIN
    SELECT COUNT(*) INTO v_prs
    FROM public.ziko_session_sets
    WHERE user_id = p_user_id
      AND is_pr = true;
  EXCEPTION WHEN undefined_column THEN
    v_prs := 0;
  END;

  v_streak := 0;
  v_streak_date := CURRENT_DATE;
  LOOP
    SELECT COUNT(*) INTO v_consecutive
    FROM public.ziko_habit_logs hl
    JOIN public.ziko_habits h ON h.id = hl.habit_id
    WHERE h.user_id = p_user_id
      AND hl.completed_at::date = v_streak_date;
    EXIT WHEN v_consecutive = 0;
    v_streak := v_streak + 1;
    v_streak_date := v_streak_date - 1;
  END LOOP;

  SELECT COUNT(*) INTO v_profile_done
  FROM public.ziko_user_profiles
  WHERE id         = p_user_id
    AND avatar_url IS NOT NULL
    AND bio        IS NOT NULL
    AND goal       IS NOT NULL;

  BEGIN
    SELECT COUNT(*) INTO v_friends
    FROM public.ziko_friendships
    WHERE user_id = p_user_id
      AND status  = 'accepted';
  EXCEPTION WHEN undefined_table THEN
    v_friends := 0;
  END;

  FOR rec IN
    SELECT bd.slug, bd.condition_type, bd.condition_value
    FROM   public.ziko_badge_definitions bd
    WHERE  NOT EXISTS (
      SELECT 1 FROM public.ziko_user_badges ub
      WHERE ub.user_id    = p_user_id
        AND ub.badge_slug = bd.slug
    )
  LOOP
    CASE rec.condition_type
      WHEN 'sessions' THEN
        IF v_sessions >= rec.condition_value THEN
          INSERT INTO public.ziko_user_badges (user_id, badge_slug)
          VALUES (p_user_id, rec.slug)
          ON CONFLICT DO NOTHING;
        END IF;
      WHEN 'streak' THEN
        IF v_streak >= rec.condition_value THEN
          INSERT INTO public.ziko_user_badges (user_id, badge_slug)
          VALUES (p_user_id, rec.slug)
          ON CONFLICT DO NOTHING;
        END IF;
      WHEN 'prs' THEN
        IF v_prs >= rec.condition_value THEN
          INSERT INTO public.ziko_user_badges (user_id, badge_slug)
          VALUES (p_user_id, rec.slug)
          ON CONFLICT DO NOTHING;
        END IF;
      WHEN 'profile_complete' THEN
        IF v_profile_done >= rec.condition_value THEN
          INSERT INTO public.ziko_user_badges (user_id, badge_slug)
          VALUES (p_user_id, rec.slug)
          ON CONFLICT DO NOTHING;
        END IF;
      WHEN 'friends' THEN
        IF v_friends >= rec.condition_value THEN
          INSERT INTO public.ziko_user_badges (user_id, badge_slug)
          VALUES (p_user_id, rec.slug)
          ON CONFLICT DO NOTHING;
        END IF;
      ELSE NULL;
    END CASE;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_claim_waitlist_signup(p_email text, p_audience text, p_locale text DEFAULT NULL::text, p_utm_source text DEFAULT NULL::text, p_utm_campaign text DEFAULT NULL::text)
 RETURNS TABLE(is_new boolean, is_founder boolean, founder_rank integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_normalized TEXT := public.ziko_normalize_waitlist_email(p_email);
  v_id         UUID;
  v_rank       INTEGER;
  v_founder    BOOLEAN;
BEGIN
  INSERT INTO public.ziko_waitlist_signups
    (email, email_normalized, audience, locale, utm_source, utm_campaign)
  VALUES
    (lower(trim(p_email)), v_normalized, p_audience, p_locale, p_utm_source, p_utm_campaign)
  ON CONFLICT (email_normalized) DO NOTHING
  RETURNING id INTO v_id;

  IF v_id IS NULL THEN
    -- Duplicate. Server-to-server only; the Server Action applies D-03/D-04.
    SELECT wl.is_founder, wl.founder_rank INTO v_founder, v_rank
    FROM public.ziko_waitlist_signups wl WHERE wl.email_normalized = v_normalized;
    RETURN QUERY SELECT false, COALESCE(v_founder, false), v_rank;
    RETURN;
  END IF;

  -- 200 is a locked business constant (REQUIREMENTS.md "Plafond fondateurs: 200 au total"),
  -- never a configurable value and never derived from a row count — nextval() is the only
  -- source of truth for who is founder #200 vs #201 under concurrency.
  v_rank    := nextval('public.ziko_waitlist_founder_seq');
  v_founder := v_rank <= 200;

  UPDATE public.ziko_waitlist_signups
  SET founder_rank = v_rank, is_founder = v_founder
  WHERE id = v_id;

  RETURN QUERY SELECT true, v_founder, v_rank;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_create_form_instances_for_trigger(p_trigger_type text, p_athlete_id uuid, p_coach_id uuid, p_n_sessions integer DEFAULT NULL::integer, p_date text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_form     RECORD;
  v_count    integer := 0;
  v_inserted integer;
BEGIN
  FOR v_form IN
    SELECT id
    FROM public.ziko_coach_forms
    WHERE coach_id = p_coach_id
      AND status = 'active'
      AND trigger_config->>'type' = p_trigger_type
      AND CASE p_trigger_type
            WHEN 'after_n_sessions' THEN
              (trigger_config->>'n_sessions')::integer = p_n_sessions
            WHEN 'fixed_date' THEN
              trigger_config->>'date' <= p_date
            ELSE TRUE
          END
  LOOP
    INSERT INTO public.ziko_form_instances(form_id, athlete_id, status)
    VALUES (v_form.id, p_athlete_id, 'pending')
    ON CONFLICT ON CONSTRAINT form_instances_no_dup_pending DO NOTHING;

    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    v_count := v_count + v_inserted;
  END LOOP;

  RETURN v_count;

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING '[create_form_instances_for_trigger] error for trigger_type=%, athlete=%, coach=%: %',
    p_trigger_type, p_athlete_id, p_coach_id, SQLERRM;
  RAISE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_deduct_ai_credits(p_user_id uuid, p_cost integer, p_action_type text, p_idempotency_key text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_balance INTEGER;
BEGIN
  -- Row lock prevents concurrent deductions racing
  SELECT balance INTO v_balance
  FROM public.ziko_user_ai_credits
  WHERE user_id = p_user_id
  FOR UPDATE;

  -- No credit row found
  IF v_balance IS NULL THEN
    RETURN jsonb_build_object('success', false, 'balance', 0, 'required', p_cost);
  END IF;

  -- Insufficient balance
  IF v_balance < p_cost THEN
    RETURN jsonb_build_object('success', false, 'balance', v_balance, 'required', p_cost);
  END IF;

  -- Deduct
  UPDATE public.ziko_user_ai_credits
  SET balance = balance - p_cost,
      updated_at = NOW()
  WHERE user_id = p_user_id;

  -- Ledger row (balance_after set by BEFORE INSERT trigger)
  INSERT INTO public.ziko_ai_credit_transactions
    (user_id, type, amount, source, idempotency_key, metadata)
  VALUES
    (p_user_id, 'deduct', -p_cost, p_action_type, p_idempotency_key, '{}'::jsonb)
  ON CONFLICT (user_id, source, idempotency_key) DO NOTHING;

  RETURN jsonb_build_object('success', true, 'balance_after', v_balance - p_cost);
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_earn_ai_credits(p_user_id uuid, p_source text, p_idempotency_key text, p_amount integer DEFAULT 1, p_daily_cap integer DEFAULT 4)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_earn_count  INTEGER;
  v_rows        INTEGER;
BEGIN
  -- Check daily earn cap (EARN-07)
  SELECT COUNT(*) INTO v_earn_count
  FROM public.ziko_ai_credit_transactions
  WHERE user_id = p_user_id
    AND type = 'earn'
    AND created_at >= (CURRENT_DATE AT TIME ZONE 'UTC');

  IF v_earn_count >= p_daily_cap THEN
    RETURN jsonb_build_object('credited', false, 'reason', 'daily_cap_reached');
  END IF;

  -- ON CONFLICT must include the WHERE clause to match the partial unique index
  -- idx_credit_tx_idempotency ON (user_id, source, idempotency_key) WHERE idempotency_key IS NOT NULL
  INSERT INTO public.ziko_ai_credit_transactions (user_id, type, amount, source, idempotency_key)
  VALUES (p_user_id, 'earn', p_amount, p_source, p_idempotency_key)
  ON CONFLICT (user_id, source, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING;

  GET DIAGNOSTICS v_rows = ROW_COUNT;

  IF v_rows = 0 THEN
    RETURN jsonb_build_object('credited', false, 'reason', 'duplicate');
  END IF;

  -- Ensure credits row exists
  INSERT INTO public.ziko_user_ai_credits (user_id, balance)
  VALUES (p_user_id, 0)
  ON CONFLICT (user_id) DO NOTHING;

  -- Increment balance
  UPDATE public.ziko_user_ai_credits
  SET balance    = balance + p_amount,
      updated_at = NOW()
  WHERE user_id = p_user_id;

  RETURN jsonb_build_object('credited', true);
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_ensure_community_stats()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
BEGIN
  INSERT INTO public.ziko_community_user_stats (user_id)
  VALUES (NEW.requester_id)
  ON CONFLICT DO NOTHING;

  INSERT INTO public.ziko_community_user_stats (user_id)
  VALUES (NEW.addressee_id)
  ON CONFLICT DO NOTHING;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_ensure_gamification_profile(p_user_id uuid)
 RETURNS ziko_user_gamification
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_profile public.ziko_user_gamification;
BEGIN
  SELECT * INTO v_profile FROM public.ziko_user_gamification WHERE user_id = p_user_id;
  IF FOUND THEN
    RETURN v_profile;
  END IF;

  INSERT INTO public.ziko_user_gamification (user_id)
  VALUES (p_user_id)
  ON CONFLICT (user_id) DO NOTHING;

  SELECT * INTO v_profile FROM public.ziko_user_gamification WHERE user_id = p_user_id;
  RETURN v_profile;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_generate_referral_code(user_id uuid)
 RETURNS text
 LANGUAGE plpgsql
 SET search_path = public, pg_temp
AS $function$
DECLARE
  handle TEXT;
  code TEXT;
BEGIN
  SELECT UPPER(COALESCE(SUBSTRING(COALESCE(u.handle, u.name, 'USER'), 1, 4), 'USER'))
  INTO handle FROM public.ziko_user_profiles u WHERE id = user_id;
  LOOP
    code := handle || '-' || UPPER(SUBSTRING(MD5(RANDOM()::TEXT), 1, 4));
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.ziko_user_profiles WHERE referral_code = code);
  END LOOP;
  RETURN code;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_get_waitlist_founder_status()
 RETURNS TABLE(should_display boolean, remaining integer, is_full boolean)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_claimed   INTEGER;
  v_threshold INTEGER;
BEGIN
  SELECT count(*) INTO v_claimed FROM public.ziko_waitlist_signups WHERE is_founder;

  SELECT (value::text)::INTEGER INTO v_threshold
  FROM public.ziko_app_config WHERE key = 'waitlist_reveal_threshold';
  v_threshold := COALESCE(v_threshold, 30);

  RETURN QUERY SELECT
    (200 - v_claimed) <= v_threshold AS should_display,
    GREATEST(200 - v_claimed, 0)     AS remaining,
    v_claimed >= 200                 AS is_full;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_grant_premium_credits(p_user_id uuid, p_amount integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_idempotency_key TEXT := 'premium_grant_' || to_char(now(), 'YYYY-MM');
  v_rows             INTEGER;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RETURN jsonb_build_object('granted', false, 'reason', 'invalid_amount');
  END IF;

  INSERT INTO public.ziko_ai_credit_transactions (user_id, type, amount, source, idempotency_key)
  VALUES (p_user_id, 'premium_grant', p_amount, 'premium_grant', v_idempotency_key)
  ON CONFLICT (user_id, source, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING;

  GET DIAGNOSTICS v_rows = ROW_COUNT;

  IF v_rows = 0 THEN
    RETURN jsonb_build_object('granted', false, 'reason', 'duplicate');
  END IF;

  INSERT INTO public.ziko_user_ai_credits (user_id, balance)
  VALUES (p_user_id, 0)
  ON CONFLICT (user_id) DO NOTHING;

  UPDATE public.ziko_user_ai_credits
  SET balance    = balance + p_amount,
      updated_at = NOW()
  WHERE user_id = p_user_id;

  RETURN jsonb_build_object('granted', true, 'amount', p_amount);
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
BEGIN
  INSERT INTO public.ziko_user_profiles (id, name)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email)
  );
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_handle_new_user_credits()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_welcome INTEGER := 5;
BEGIN
  INSERT INTO public.ziko_user_ai_credits (user_id, balance)
  VALUES (NEW.id, v_welcome)
  ON CONFLICT (user_id) DO NOTHING;

  INSERT INTO public.ziko_ai_credit_transactions (user_id, type, amount, source)
  VALUES (NEW.id, 'welcome', v_welcome, 'signup');

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_handle_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = public, pg_temp
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_increment_community_stat(p_user_id uuid, p_field text, p_amount integer DEFAULT 1)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_field NOT IN (
    'messages_sent', 'gifs_sent', 'reactions_sent',
    'challenges_won', 'challenges_lost', 'challenges_tied',
    'xp_gifted', 'xp_received', 'coins_gifted', 'coins_received',
    'programs_shared', 'group_workouts_done',
    'encouragements_sent', 'encouragements_received',
    'invites_sent', 'invites_accepted'
  ) THEN
    RAISE EXCEPTION 'increment_community_stat: invalid field %', p_field;
  END IF;

  INSERT INTO public.ziko_community_user_stats (user_id) VALUES (p_user_id)
  ON CONFLICT (user_id) DO NOTHING;

  EXECUTE format(
    'UPDATE public.ziko_community_user_stats SET %I = %I + $1, updated_at = NOW() WHERE user_id = $2',
    p_field, p_field
  ) USING p_amount, p_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_is_coach_of(coach uuid, client uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.ziko_coach_client_links
    WHERE coach_id = coach
      AND client_id = client
      AND revoked_at IS NULL
      AND (expires_at IS NULL OR expires_at > now())
  );
$function$;

CREATE OR REPLACE FUNCTION public.ziko_normalize_waitlist_email(p_email text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path = public, pg_temp
AS $function$
DECLARE
  v_email  TEXT := lower(trim(p_email));
  v_at     INTEGER := position('@' in lower(trim(p_email)));
  v_local  TEXT;
  v_domain TEXT;
BEGIN
  IF v_at = 0 THEN
    RETURN v_email;
  END IF;

  v_local  := substring(v_email from 1 for v_at - 1);
  v_domain := substring(v_email from v_at + 1);

  -- +suffix stripped for ALL domains (D-10)
  v_local := split_part(v_local, '+', 1);

  -- Dots stripped ONLY for Gmail/Googlemail — not universal (D-10, Pitfall 5)
  IF v_domain IN ('gmail.com', 'googlemail.com') THEN
    v_local := replace(v_local, '.', '');
  END IF;

  RETURN v_local || '@' || v_domain;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_peek_invitation(code_input text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_caller_id UUID := auth.uid();
  v_inv       RECORD;
  v_error     TEXT := NULL;
BEGIN
  SELECT
    inv.id            AS id,
    inv.coach_id      AS coach_id,
    inv.expires_at    AS expires_at,
    inv.revoked_at    AS revoked_at,
    inv.use_count     AS use_count,
    inv.max_uses      AS max_uses,
    EXISTS (
      SELECT 1 FROM public.ziko_coach_client_links l
      WHERE l.coach_id = inv.coach_id
        AND l.client_id = v_caller_id
        AND l.revoked_at IS NULL
        AND (l.expires_at IS NULL OR l.expires_at > now())
    )                  AS link_exists,
    cp.display_name   AS display_name,
    cp.bio            AS bio,
    cp.specialties    AS specialties,
    cp.photo_url      AS photo_url,
    cp.kyc_status     AS kyc_status
  INTO v_inv
  FROM public.ziko_coach_invitations inv
  LEFT JOIN public.ziko_coach_profiles cp ON cp.user_id = inv.coach_id
  WHERE inv.code = code_input
  LIMIT 1;

  IF v_inv.id IS NULL THEN
    v_error := 'INVALID_CODE';
  ELSIF v_inv.coach_id = v_caller_id THEN
    v_error := 'SELF_INVITATION';
  ELSIF v_inv.revoked_at IS NOT NULL THEN
    v_error := 'REVOKED';
  ELSIF v_inv.expires_at IS NOT NULL AND v_inv.expires_at <= now() THEN
    v_error := 'EXPIRED';
  ELSIF v_inv.use_count >= v_inv.max_uses THEN
    v_error := 'ALREADY_USED';
  ELSIF v_inv.link_exists THEN
    v_error := 'LINK_EXISTS';
  END IF;

  IF v_error IS NOT NULL THEN
    RETURN jsonb_build_object('ok', false, 'preview', NULL, 'error_code', v_error);
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'error_code', NULL,
    'preview', jsonb_build_object(
      'coach_id', v_inv.coach_id,
      'display_name', v_inv.display_name,
      'bio', v_inv.bio,
      'specialties', v_inv.specialties,
      'photo_url', v_inv.photo_url,
      'kyc_status', v_inv.kyc_status
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_purchase_shop_item(p_user_id uuid, p_item_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_profile public.ziko_user_gamification;
  v_item    public.ziko_shop_items;
  v_rows    INTEGER;
BEGIN
  v_profile := public.ziko_ensure_gamification_profile(p_user_id);

  SELECT * INTO v_item FROM public.ziko_shop_items WHERE id = p_item_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Article introuvable');
  END IF;

  IF v_profile.level < v_item.level_required THEN
    RETURN jsonb_build_object('success', false, 'error', format('Niveau %s requis', v_item.level_required));
  END IF;

  IF EXISTS (SELECT 1 FROM public.ziko_user_inventory WHERE user_id = p_user_id AND item_id = p_item_id) THEN
    RETURN jsonb_build_object('success', false, 'error', 'Déjà possédé');
  END IF;

  -- Atomic guarded deduction — fails (0 rows) if balance is insufficient,
  -- closing the race where two purchases could both pass a stale balance check.
  UPDATE public.ziko_user_gamification
  SET coins = coins - v_item.price, updated_at = NOW()
  WHERE user_id = p_user_id AND coins >= v_item.price;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows = 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Pas assez de pièces');
  END IF;

  INSERT INTO public.ziko_coin_transactions (user_id, amount, source, source_id, description)
  VALUES (p_user_id, -v_item.price, 'purchase', p_item_id, format('🛒 Achat : %s', v_item.name));

  INSERT INTO public.ziko_user_inventory (user_id, item_id)
  VALUES (p_user_id, p_item_id);

  RETURN jsonb_build_object('success', true);
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_record_athlete_decision(p_user_id uuid, p_decision_type text, p_week_of date, p_summary text, p_rationale text, p_evidence jsonb, p_outcome jsonb, p_source text, p_state_patch jsonb, p_new_goal jsonb DEFAULT NULL::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_decision_id UUID;
  v_goal_id     UUID;
  v_rows        INTEGER;
BEGIN
  -- (a) Guard first, before touching any table. Return an error-shaped
  -- JSONB, never RAISE EXCEPTION — matching grant_premium_credits's
  -- invalid_amount guard. FOUND-02: an ungrounded decision is unwritable.
  IF p_evidence IS NULL OR jsonb_typeof(p_evidence) <> 'object' THEN
    RETURN jsonb_build_object('success', false, 'error', 'evidence_required');
  END IF;

  -- (b) Journal insert. ON CONFLICT column list and predicate must match
  -- idx_athlete_decisions_week_idempotency character-for-character
  -- (20260831120100_athlete_decisions.sql) or Postgres cannot infer the
  -- arbiter index.
  INSERT INTO public.ziko_athlete_decisions
    (user_id, decision_type, week_of, summary, rationale, evidence, outcome, source)
  VALUES (
    p_user_id, p_decision_type, p_week_of, p_summary, p_rationale, p_evidence,
    COALESCE(p_outcome, '{}'::jsonb), COALESCE(p_source, 'weekly_review_cron')
  )
  ON CONFLICT (user_id, decision_type, week_of)
    WHERE decision_type = 'weekly_focus' AND week_of IS NOT NULL DO NOTHING
  RETURNING id INTO v_decision_id;

  -- (c) Duplicate detection. Zero rows affected means this athlete already
  -- has a weekly_focus decision recorded for this week — return immediately,
  -- before the goal insert or state patch is applied. This early return is
  -- the entire idempotency guarantee (ENGINE-04): moving either below it
  -- would silently re-apply the patch (or create an orphan goal row) on
  -- every at-least-once cron retry.
  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows = 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'duplicate');
  END IF;

  -- (NEW, D-09) Insert athlete_goals BEFORE the state patch, inside the
  -- same transaction, so current_focus_detail.goal_id can reference the
  -- real row atomically rather than a placeholder.
  IF p_new_goal IS NOT NULL THEN
    INSERT INTO public.ziko_athlete_goals (user_id, goal_text, target_metric, target_value, target_date, status)
    VALUES (
      p_user_id,
      p_new_goal->>'goal_text',
      p_new_goal->>'target_metric',
      (p_new_goal->>'target_value')::numeric,
      (p_new_goal->>'target_date')::date,
      COALESCE(p_new_goal->>'status', 'active')
    )
    RETURNING id INTO v_goal_id;
  END IF;

  -- (d) Self-heal the parent row: the first-ever decision for an athlete
  -- (Phase 43 onboarding) creates athlete_state with schema defaults
  -- (readiness='fragile', level=1, tier=1, points=0, status='onboarding')
  -- before the UPDATE below patches it.
  INSERT INTO public.ziko_athlete_state (user_id)
  VALUES (p_user_id)
  ON CONFLICT (user_id) DO NOTHING;

  -- (e) Patch the state row. p_state_patch accepts any subset of the
  -- recognised keys below; an absent key leaves the column unchanged
  -- (COALESCE against the current column value).
  UPDATE public.ziko_athlete_state
  SET
    -- level: plain COALESCE, deliberately NOT ratcheted. ENGINE-03
    -- explicitly requires Phase 44's weekly engine to be able to
    -- de-escalate as well as escalate, so level must remain freely
    -- settable; the `level >= 1` CHECK on the column is the floor.
    level = COALESCE((p_state_patch->>'level')::int, level),

    -- points/tier: monotonic ratchet via GREATEST. REWARD-04 requires
    -- unlocked tiers/points to never be revoked or decreased, and this
    -- RPC is the only place that invariant can be enforced at the DB
    -- layer (research/PITFALLS.md Pitfall 5 — a buggy caller passing a
    -- lower value must not silently decrease either field).
    points = GREATEST(points, COALESCE((p_state_patch->>'points')::int, points)),
    tier   = GREATEST(tier, COALESCE((p_state_patch->>'tier')::int, tier)),

    readiness              = COALESCE(p_state_patch->>'readiness', readiness),
    status                 = COALESCE(p_state_patch->>'status', status),
    current_focus_summary  = COALESCE(p_state_patch->>'current_focus_summary', current_focus_summary),
    -- JSONB-valued keys use the `->` arrow (not `->>`) to preserve the
    -- JSONB type rather than casting to text. Delta 1 (D-09): fold in the
    -- real goal id instead of relying on a caller-supplied placeholder —
    -- callers never pass a $NEW_GOAL_ID marker; they pass the merged
    -- detail object without goal_id and this RPC stamps the real id
    -- atomically once the athlete_goals row above exists.
    current_focus_detail   = COALESCE(p_state_patch->'current_focus_detail', current_focus_detail)
                              || CASE WHEN v_goal_id IS NOT NULL
                                   THEN jsonb_build_object('goal_id', v_goal_id)
                                   ELSE '{}'::jsonb
                                 END,
    onboarding_profile     = COALESCE(p_state_patch->'onboarding_profile', onboarding_profile),
    rolling_summary        = COALESCE(p_state_patch->>'rolling_summary', rolling_summary),

    -- last_review_at/next_review_due_at: last_review_at keeps its current
    -- weekly_focus-only behaviour unchanged. Delta 2 (D-02/Pitfall-4 fix):
    -- next_review_due_at now ALSO stamps on 'onboarding_profile', so the
    -- cadence rolls from the athlete's onboarding completion date instead
    -- of only after the second-ever decision. goal_created, program_created,
    -- reward_grant and level_change must NOT move the clock.
    last_review_at     = CASE WHEN p_decision_type = 'weekly_focus' THEN NOW() ELSE last_review_at END,
    next_review_due_at = CASE WHEN p_decision_type IN ('weekly_focus', 'onboarding_profile') THEN NOW() + INTERVAL '7 days' ELSE next_review_due_at END,

    -- Belt-and-braces alongside trg_athlete_state_updated.
    updated_at = NOW()
  WHERE user_id = p_user_id;

  -- (f) Success.
  RETURN jsonb_build_object('success', true, 'decision_id', v_decision_id, 'goal_id', v_goal_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_redeem_invitation_code(code_input text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_caller_id    UUID := auth.uid();
  v_inv          RECORD;
  v_new_link_id  UUID;
  v_error        TEXT := NULL;
BEGIN
  SELECT
    inv.id            AS id,
    inv.coach_id      AS coach_id,
    inv.expires_at    AS expires_at,
    inv.revoked_at    AS revoked_at,
    inv.used_at       AS used_at,
    inv.use_count     AS use_count,
    inv.max_uses      AS max_uses,
    EXISTS (
      SELECT 1 FROM public.ziko_coach_client_links l
      WHERE l.coach_id = inv.coach_id
        AND l.client_id = v_caller_id
        AND l.revoked_at IS NULL
        AND (l.expires_at IS NULL OR l.expires_at > now())
    )                  AS link_exists
  INTO v_inv
  FROM public.ziko_coach_invitations inv
  WHERE inv.code = code_input
  LIMIT 1;

  IF v_inv.id IS NULL THEN
    v_error := 'INVALID_CODE';
  ELSIF v_inv.coach_id = v_caller_id THEN
    v_error := 'SELF_INVITATION';
  ELSIF v_inv.revoked_at IS NOT NULL THEN
    v_error := 'REVOKED';
  ELSIF v_inv.expires_at <= now() THEN
    v_error := 'EXPIRED';
  ELSIF v_inv.use_count >= v_inv.max_uses THEN
    v_error := 'ALREADY_USED';
  ELSIF v_inv.link_exists THEN
    v_error := 'LINK_EXISTS';
  END IF;

  IF v_error IS NOT NULL THEN
    RETURN jsonb_build_object('ok', false, 'link_id', NULL, 'error_code', v_error);
  END IF;

  INSERT INTO public.ziko_coach_client_links (coach_id, client_id)
  VALUES (v_inv.coach_id, v_caller_id)
  RETURNING id INTO v_new_link_id;

  UPDATE public.ziko_coach_invitations
  SET use_count = use_count + 1,
      used_at   = COALESCE(used_at, now()),
      used_by   = COALESCE(used_by, v_caller_id)
  WHERE id = v_inv.id;

  RETURN jsonb_build_object('ok', true, 'link_id', v_new_link_id, 'error_code', NULL);
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_reset_waitlist_founder_sequence(p_next_value bigint)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF p_next_value < 1 THEN
    RAISE EXCEPTION 'p_next_value must be >= 1, got %', p_next_value;
  END IF;

  PERFORM setval('public.ziko_waitlist_founder_seq', p_next_value, false);
  RETURN p_next_value;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_search_users_fuzzy(search_query text, calling_user_id uuid, result_limit integer DEFAULT 20)
 RETURNS TABLE(id uuid, name text, avatar_url text, goal text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path = public, extensions, pg_temp
AS $function$
  SELECT
    p.id,
    p.name,
    p.avatar_url,
    p.goal
  FROM public.ziko_user_profiles p
  WHERE
    p.id <> calling_user_id
    AND unaccent(lower(p.name)) LIKE '%' || unaccent(lower(search_query)) || '%'
  ORDER BY
    -- Exact match (after normalization) ranked first
    CASE WHEN unaccent(lower(p.name)) = unaccent(lower(search_query)) THEN 0 ELSE 1 END,
    -- Prefix match ranked second
    CASE WHEN unaccent(lower(p.name)) LIKE unaccent(lower(search_query)) || '%' THEN 0 ELSE 1 END,
    p.name
  LIMIT result_limit;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_send_coin_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_rows INTEGER;
BEGIN
  IF p_amount <= 0 OR p_amount > 1000 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Montant invalide (1-1000)');
  END IF;
  IF p_sender_id = p_receiver_id THEN
    RETURN jsonb_build_object('success', false, 'error', 'Impossible de s''auto-offrir des pièces');
  END IF;

  PERFORM public.ziko_ensure_gamification_profile(p_sender_id);
  PERFORM public.ziko_ensure_gamification_profile(p_receiver_id);

  -- Atomic guarded debit — fails (0 rows) if balance is insufficient
  UPDATE public.ziko_user_gamification
  SET coins = coins - p_amount, updated_at = NOW()
  WHERE user_id = p_sender_id AND coins >= p_amount;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  IF v_rows = 0 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Pas assez de pièces');
  END IF;

  UPDATE public.ziko_user_gamification
  SET coins = coins + p_amount, updated_at = NOW()
  WHERE user_id = p_receiver_id;

  INSERT INTO public.ziko_coin_gifts (sender_id, receiver_id, amount, message)
  VALUES (p_sender_id, p_receiver_id, p_amount, p_message);

  PERFORM public.ziko_increment_community_stat(p_sender_id, 'coins_gifted', p_amount);
  PERFORM public.ziko_increment_community_stat(p_receiver_id, 'coins_received', p_amount);

  RETURN jsonb_build_object('success', true);
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_send_xp_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_amount <= 0 OR p_amount > 5000 THEN
    RETURN jsonb_build_object('success', false, 'error', 'Montant invalide (1-5000)');
  END IF;
  IF p_sender_id = p_receiver_id THEN
    RETURN jsonb_build_object('success', false, 'error', 'Impossible de s''auto-offrir de l''XP');
  END IF;

  INSERT INTO public.ziko_xp_gifts (sender_id, receiver_id, amount, message)
  VALUES (p_sender_id, p_receiver_id, p_amount, p_message);

  PERFORM public.ziko_increment_community_stat(p_sender_id, 'xp_gifted', p_amount);
  PERFORM public.ziko_increment_community_stat(p_receiver_id, 'xp_received', p_amount);

  RETURN jsonb_build_object('success', true);
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_set_credit_transaction_balance_after()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  SELECT balance INTO NEW.balance_after
  FROM public.ziko_user_ai_credits
  WHERE user_id = NEW.user_id;

  IF NEW.balance_after IS NULL THEN
    NEW.balance_after := 0;
  END IF;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_unlock_default_theme()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
DECLARE
  v_item_id UUID;
BEGIN
  SELECT id INTO v_item_id
  FROM public.ziko_shop_items
  WHERE name = 'Sport Orange'
  LIMIT 1;

  IF v_item_id IS NOT NULL THEN
    INSERT INTO public.ziko_user_inventory (user_id, item_id)
    VALUES (NEW.id, v_item_id)
    ON CONFLICT (user_id, item_id) DO NOTHING;
  END IF;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_update_post_comments_count()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.ziko_community_posts SET comments_count = comments_count + 1 WHERE id = NEW.post_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.ziko_community_posts SET comments_count = GREATEST(0, comments_count - 1) WHERE id = OLD.post_id;
  END IF;
  RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_update_post_likes_count()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public, pg_temp
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.ziko_community_posts SET likes_count = likes_count + 1 WHERE id = NEW.post_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.ziko_community_posts SET likes_count = GREATEST(0, likes_count - 1) WHERE id = OLD.post_id;
  END IF;
  RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.ziko_update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = public, pg_temp
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

-- ── Function privileges (replicates ziko live ACLs) ─────────────────────
REVOKE ALL ON FUNCTION public.ziko_anonymize_waitlist_signup(p_email text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_anonymize_waitlist_signup(p_email text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_award_coins(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_award_coins(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_award_coins(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_award_coins(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_award_coins(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_award_xp(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_award_xp(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_award_xp(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_award_xp(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_award_xp(p_user_id uuid, p_amount integer, p_source text, p_source_id uuid, p_description text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_check_and_award_badges(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_check_and_award_badges(p_user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_check_and_award_badges(p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_check_and_award_badges(p_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_check_and_award_badges(p_user_id uuid) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_claim_waitlist_signup(p_email text, p_audience text, p_locale text, p_utm_source text, p_utm_campaign text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_claim_waitlist_signup(p_email text, p_audience text, p_locale text, p_utm_source text, p_utm_campaign text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_create_form_instances_for_trigger(p_trigger_type text, p_athlete_id uuid, p_coach_id uuid, p_n_sessions integer, p_date text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_create_form_instances_for_trigger(p_trigger_type text, p_athlete_id uuid, p_coach_id uuid, p_n_sessions integer, p_date text) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_create_form_instances_for_trigger(p_trigger_type text, p_athlete_id uuid, p_coach_id uuid, p_n_sessions integer, p_date text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_create_form_instances_for_trigger(p_trigger_type text, p_athlete_id uuid, p_coach_id uuid, p_n_sessions integer, p_date text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_deduct_ai_credits(p_user_id uuid, p_cost integer, p_action_type text, p_idempotency_key text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_deduct_ai_credits(p_user_id uuid, p_cost integer, p_action_type text, p_idempotency_key text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_deduct_ai_credits(p_user_id uuid, p_cost integer, p_action_type text, p_idempotency_key text) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_deduct_ai_credits(p_user_id uuid, p_cost integer, p_action_type text, p_idempotency_key text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_deduct_ai_credits(p_user_id uuid, p_cost integer, p_action_type text, p_idempotency_key text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_earn_ai_credits(p_user_id uuid, p_source text, p_idempotency_key text, p_amount integer, p_daily_cap integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_earn_ai_credits(p_user_id uuid, p_source text, p_idempotency_key text, p_amount integer, p_daily_cap integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_earn_ai_credits(p_user_id uuid, p_source text, p_idempotency_key text, p_amount integer, p_daily_cap integer) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_earn_ai_credits(p_user_id uuid, p_source text, p_idempotency_key text, p_amount integer, p_daily_cap integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_earn_ai_credits(p_user_id uuid, p_source text, p_idempotency_key text, p_amount integer, p_daily_cap integer) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_ensure_community_stats() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_ensure_community_stats() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_ensure_community_stats() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_ensure_community_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_ensure_community_stats() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_ensure_gamification_profile(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_ensure_gamification_profile(p_user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_ensure_gamification_profile(p_user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_ensure_gamification_profile(p_user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_ensure_gamification_profile(p_user_id uuid) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_generate_referral_code(user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_generate_referral_code(user_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_generate_referral_code(user_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_generate_referral_code(user_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_generate_referral_code(user_id uuid) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_get_waitlist_founder_status() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_get_waitlist_founder_status() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_grant_premium_credits(p_user_id uuid, p_amount integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_grant_premium_credits(p_user_id uuid, p_amount integer) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_handle_new_user() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_handle_new_user() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_handle_new_user() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_handle_new_user() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_handle_new_user() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_handle_new_user_credits() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_handle_new_user_credits() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_handle_new_user_credits() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_handle_new_user_credits() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_handle_new_user_credits() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_handle_updated_at() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_handle_updated_at() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_handle_updated_at() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_handle_updated_at() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_handle_updated_at() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_increment_community_stat(p_user_id uuid, p_field text, p_amount integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_increment_community_stat(p_user_id uuid, p_field text, p_amount integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_increment_community_stat(p_user_id uuid, p_field text, p_amount integer) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_increment_community_stat(p_user_id uuid, p_field text, p_amount integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_increment_community_stat(p_user_id uuid, p_field text, p_amount integer) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_is_coach_of(coach uuid, client uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_is_coach_of(coach uuid, client uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_is_coach_of(coach uuid, client uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_is_coach_of(coach uuid, client uuid) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_normalize_waitlist_email(p_email text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_normalize_waitlist_email(p_email text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_peek_invitation(code_input text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_peek_invitation(code_input text) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_peek_invitation(code_input text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_peek_invitation(code_input text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_purchase_shop_item(p_user_id uuid, p_item_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_purchase_shop_item(p_user_id uuid, p_item_id uuid) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_purchase_shop_item(p_user_id uuid, p_item_id uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_purchase_shop_item(p_user_id uuid, p_item_id uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_purchase_shop_item(p_user_id uuid, p_item_id uuid) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_record_athlete_decision(p_user_id uuid, p_decision_type text, p_week_of date, p_summary text, p_rationale text, p_evidence jsonb, p_outcome jsonb, p_source text, p_state_patch jsonb, p_new_goal jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_record_athlete_decision(p_user_id uuid, p_decision_type text, p_week_of date, p_summary text, p_rationale text, p_evidence jsonb, p_outcome jsonb, p_source text, p_state_patch jsonb, p_new_goal jsonb) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_redeem_invitation_code(code_input text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_redeem_invitation_code(code_input text) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_redeem_invitation_code(code_input text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_redeem_invitation_code(code_input text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_reset_waitlist_founder_sequence(p_next_value bigint) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_reset_waitlist_founder_sequence(p_next_value bigint) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_rls_auto_enable() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_rls_auto_enable() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_rls_auto_enable() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_rls_auto_enable() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_rls_auto_enable() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_search_users_fuzzy(search_query text, calling_user_id uuid, result_limit integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_search_users_fuzzy(search_query text, calling_user_id uuid, result_limit integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_search_users_fuzzy(search_query text, calling_user_id uuid, result_limit integer) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_search_users_fuzzy(search_query text, calling_user_id uuid, result_limit integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_search_users_fuzzy(search_query text, calling_user_id uuid, result_limit integer) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_send_coin_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_send_coin_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_send_coin_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_send_coin_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_send_coin_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_send_xp_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_send_xp_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_send_xp_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_send_xp_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_send_xp_gift(p_sender_id uuid, p_receiver_id uuid, p_amount integer, p_message text) TO service_role;
REVOKE ALL ON FUNCTION public.ziko_set_credit_transaction_balance_after() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_set_credit_transaction_balance_after() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_set_credit_transaction_balance_after() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_set_credit_transaction_balance_after() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_set_credit_transaction_balance_after() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_unlock_default_theme() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_unlock_default_theme() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_unlock_default_theme() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_unlock_default_theme() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_unlock_default_theme() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_update_post_comments_count() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_update_post_comments_count() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_update_post_comments_count() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_update_post_comments_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_update_post_comments_count() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_update_post_likes_count() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_update_post_likes_count() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_update_post_likes_count() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_update_post_likes_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_update_post_likes_count() TO service_role;
REVOKE ALL ON FUNCTION public.ziko_update_updated_at_column() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ziko_update_updated_at_column() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ziko_update_updated_at_column() TO anon;
GRANT EXECUTE ON FUNCTION public.ziko_update_updated_at_column() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ziko_update_updated_at_column() TO service_role;

RESET check_function_bodies;

-- ── Triggers (public-schema tables only) ──────────────────────────────
CREATE TRIGGER trg_conversations_updated BEFORE UPDATE ON public.ziko_ai_conversations FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER trg_credit_transaction_balance_after BEFORE INSERT ON public.ziko_ai_credit_transactions FOR EACH ROW EXECUTE FUNCTION ziko_set_credit_transaction_balance_after();
CREATE TRIGGER trg_ai_imports_updated BEFORE UPDATE ON public.ziko_ai_imports FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER trg_athlete_goals_updated BEFORE UPDATE ON public.ziko_athlete_goals FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER trg_athlete_state_updated BEFORE UPDATE ON public.ziko_athlete_state FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER trg_coach_branding_updated BEFORE UPDATE ON public.ziko_coach_branding FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER trg_coach_profiles_updated BEFORE UPDATE ON public.ziko_coach_profiles FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER trg_ensure_community_stats AFTER INSERT ON public.ziko_friendships FOR EACH ROW EXECUTE FUNCTION ziko_ensure_community_stats();
CREATE TRIGGER trg_persona_updated BEFORE UPDATE ON public.ziko_persona_settings FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER update_plugin_reviews_updated_at BEFORE UPDATE ON public.ziko_plugin_reviews FOR EACH ROW EXECUTE FUNCTION ziko_update_updated_at_column();
CREATE TRIGGER trg_post_comments_count AFTER INSERT OR DELETE ON public.ziko_post_comments FOR EACH ROW EXECUTE FUNCTION ziko_update_post_comments_count();
CREATE TRIGGER trg_post_likes_count AFTER INSERT OR DELETE ON public.ziko_post_likes FOR EACH ROW EXECUTE FUNCTION ziko_update_post_likes_count();
CREATE TRIGGER trg_user_ai_credits_updated BEFORE UPDATE ON public.ziko_user_ai_credits FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER push_user_xp_level_up AFTER UPDATE ON public.ziko_user_gamification FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://api.ziko-app.com/push-events/supabase', 'POST', '{"Content-type":"application/json","X-Webhook-Secret":"{{X_WEBHOOK_SECRET}}"}', '{}', '5000');
CREATE TRIGGER trg_unlock_default_theme AFTER INSERT ON public.ziko_user_profiles FOR EACH ROW EXECUTE FUNCTION ziko_unlock_default_theme();
CREATE TRIGGER trg_user_profiles_updated BEFORE UPDATE ON public.ziko_user_profiles FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER trg_programs_updated BEFORE UPDATE ON public.ziko_workout_programs FOR EACH ROW EXECUTE FUNCTION ziko_handle_updated_at();
CREATE TRIGGER push_workout_session_end AFTER UPDATE ON public.ziko_workout_sessions FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://api.ziko-app.com/push-events/supabase', 'POST', '{"Content-type":"application/json","X-Webhook-Secret":"{{X_WEBHOOK_SECRET}}"}', '{}', '5000');

-- ── RLS policies that call a ziko_ function (need the function to exist) ────
CREATE POLICY "body_measurements_coach_read" ON public.ziko_body_measurements AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));
CREATE POLICY "cardio_sessions_coach_read" ON public.ziko_cardio_sessions AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));
CREATE POLICY "coach_branding_athlete_read" ON public.ziko_coach_branding AS PERMISSIVE FOR SELECT USING (ziko_is_coach_of(coach_id, auth.uid()));
CREATE POLICY "coach_client_videos_coach_read" ON public.ziko_coach_client_videos AS PERMISSIVE FOR SELECT USING (ziko_is_coach_of(auth.uid(), athlete_id));
CREATE POLICY "form_instances_coach" ON public.ziko_form_instances AS PERMISSIVE FOR SELECT USING ((ziko_is_coach_of(auth.uid(), athlete_id) OR (EXISTS ( SELECT 1
   FROM ziko_coach_forms cf
  WHERE ((cf.id = ziko_form_instances.form_id) AND (cf.coach_id = auth.uid()))))));
CREATE POLICY "form_responses_coach_read" ON public.ziko_form_responses AS PERMISSIVE FOR SELECT USING (ziko_is_coach_of(auth.uid(), athlete_id));
CREATE POLICY "habit_logs_coach_read" ON public.ziko_habit_logs AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));
CREATE POLICY "habits_coach_read" ON public.ziko_habits AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));
CREATE POLICY "hydration_logs_coach_read" ON public.ziko_hydration_logs AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));
CREATE POLICY "journal_entries_coach_read" ON public.ziko_journal_entries AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));
CREATE POLICY "nutrition_logs_coach_read" ON public.ziko_nutrition_logs AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));
CREATE POLICY "program_exercises_coach_read" ON public.ziko_program_exercises AS PERMISSIVE FOR SELECT USING ((workout_id IN ( SELECT pw.id
   FROM (ziko_program_workouts pw
     JOIN ziko_workout_programs wp ON ((wp.id = pw.program_id)))
  WHERE ziko_is_coach_of(auth.uid(), wp.user_id))));
CREATE POLICY "program_workouts_coach_read" ON public.ziko_program_workouts AS PERMISSIVE FOR SELECT USING ((program_id IN ( SELECT ziko_workout_programs.id
   FROM ziko_workout_programs
  WHERE ziko_is_coach_of(auth.uid(), ziko_workout_programs.user_id))));
CREATE POLICY "session_sets_coach_read" ON public.ziko_session_sets AS PERMISSIVE FOR SELECT USING ((EXISTS ( SELECT 1
   FROM ziko_workout_sessions ws
  WHERE ((ws.id = ziko_session_sets.session_id) AND ((auth.uid() = ws.user_id) OR ziko_is_coach_of(auth.uid(), ws.user_id))))));
CREATE POLICY "sleep_logs_coach_read" ON public.ziko_sleep_logs AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));
CREATE POLICY "stretching_logs_coach_read" ON public.ziko_stretching_logs AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));
CREATE POLICY "user_profiles_coach_read" ON public.ziko_user_profiles AS PERMISSIVE FOR SELECT USING (((auth.uid() = id) OR ziko_is_coach_of(auth.uid(), id)));
CREATE POLICY "workout_programs_client_coach_update" ON public.ziko_workout_programs AS PERMISSIVE FOR UPDATE USING (ziko_is_coach_of(auth.uid(), user_id)) WITH CHECK (ziko_is_coach_of(auth.uid(), user_id));
CREATE POLICY "workout_programs_client_own_coach_read" ON public.ziko_workout_programs AS PERMISSIVE FOR SELECT USING (ziko_is_coach_of(auth.uid(), user_id));
CREATE POLICY "workout_programs_coach_assign" ON public.ziko_workout_programs AS PERMISSIVE FOR INSERT WITH CHECK (((created_by_coach_id = auth.uid()) AND (assigned_to_user_id IS NOT NULL) AND ziko_is_coach_of(auth.uid(), assigned_to_user_id)));
CREATE POLICY "workout_programs_coach_read" ON public.ziko_workout_programs AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ((assigned_to_user_id IS NOT NULL) AND ziko_is_coach_of(auth.uid(), assigned_to_user_id)) OR ((is_template = true) AND (created_by_coach_id IS NULL))));
CREATE POLICY "workout_sessions_coach_read" ON public.ziko_workout_sessions AS PERMISSIVE FOR SELECT USING (((auth.uid() = user_id) OR ziko_is_coach_of(auth.uid(), user_id)));

