-- 054 — Notifications: push tokens, log, preferences
-- ============================================================
-- NOTIFICATIONS — push tokens, log, preferences
-- Migration 054
-- ============================================================

-- ── notification_tokens ──────────────────────────────────────
-- One row per (user, device). UPSERT on registration.
CREATE TABLE IF NOT EXISTS public.notification_tokens (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  device_id   TEXT NOT NULL,          -- stable UUID generated by mobile, stored in MMKV
  token       TEXT NOT NULL,          -- ExponentPushToken[xxxx...]
  platform    TEXT NOT NULL CHECK (platform IN ('ios', 'android')),
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, device_id)         -- idempotent UPSERT target
);

CREATE INDEX idx_notification_tokens_user ON public.notification_tokens(user_id) WHERE is_active = TRUE;

ALTER TABLE public.notification_tokens ENABLE ROW LEVEL SECURITY;

-- Users can only read/write their own tokens
CREATE POLICY "notification_tokens_own"
  ON public.notification_tokens
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Backend service (server-side, bypasses RLS via service key or trusted context)
-- needs to UPDATE is_active = false when DeviceNotRegistered — this is done server-side
-- where RLS is bypassed by the admin client.


-- ── notification_log ─────────────────────────────────────────
-- Every notification ever sent or attempted. Source of truth for the in-app inbox.
CREATE TABLE IF NOT EXISTS public.notification_log (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id          UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  category         TEXT NOT NULL CHECK (category IN ('coach','workout','gamification','health','system')),
  type             TEXT NOT NULL,     -- e.g. 'program_assigned', 'level_up', 'streak_at_risk'
  title            TEXT NOT NULL,
  body             TEXT NOT NULL,
  data             JSONB,             -- { url, entityId, ... }
  idempotency_key  TEXT NOT NULL UNIQUE,  -- prevents duplicate sends
  status           TEXT NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending','sent','delivered','failed','skipped')),
  receipt_ids      TEXT[],            -- Expo push ticket IDs, for receipt polling
  error_code       TEXT,              -- 'DeviceNotRegistered', 'MessageTooBig', etc.
  read_at          TIMESTAMPTZ,       -- NULL = unread
  sent_at          TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notification_log_user ON public.notification_log(user_id, created_at DESC);
CREATE INDEX idx_notification_log_unread ON public.notification_log(user_id) WHERE read_at IS NULL;
CREATE INDEX idx_notification_log_status ON public.notification_log(status) WHERE status = 'sent';
-- last index supports the receipt-check cron: find all 'sent' rows with receipt_ids to check

ALTER TABLE public.notification_log ENABLE ROW LEVEL SECURITY;

-- Users can read and update (mark read) their own notifications
CREATE POLICY "notification_log_read"
  ON public.notification_log
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "notification_log_mark_read"
  ON public.notification_log
  FOR UPDATE USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- INSERT and status updates are done server-side only (admin client, bypasses RLS).
-- No INSERT policy for authenticated users — they should not create log rows directly.


-- ── notification_preferences ──────────────────────────────────
-- Per-user, per-category preferences. One row per user (UPSERT on change).
CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  -- Master switch
  push_enabled     BOOLEAN NOT NULL DEFAULT TRUE,
  -- Category switches
  coach_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
  workout_enabled  BOOLEAN NOT NULL DEFAULT TRUE,
  gamification_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  health_enabled   BOOLEAN NOT NULL DEFAULT TRUE,
  system_enabled   BOOLEAN NOT NULL DEFAULT TRUE,  -- not toggleable in UI but stored
  -- Granular type switches (JSONB for flexibility without schema migrations per new type)
  type_prefs       JSONB NOT NULL DEFAULT '{"program_assigned":true,"program_modified":true,"ai_weekly_analysis":true,"invitation_received":true,"invitation_accepted":true,"workout_reminder":false,"streak_at_risk":true,"post_session_summary":true,"level_up":true,"badge_unlocked":true,"weekly_xp_digest":false,"habit_reminder":false,"hydration_checkin":false,"sleep_reminder":false,"new_plugin":false}',
  -- Quiet hours (stored as simple hour integers, interpreted in UTC by server)
  quiet_hours_start INTEGER DEFAULT 22 CHECK (quiet_hours_start BETWEEN 0 AND 23),
  quiet_hours_end   INTEGER DEFAULT 7  CHECK (quiet_hours_end BETWEEN 0 AND 23),
  -- User's UTC offset for quiet hour calculation (e.g. 2 for UTC+2)
  timezone_offset   INTEGER DEFAULT 1  CHECK (timezone_offset BETWEEN -12 AND 14),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "notification_preferences_own"
  ON public.notification_preferences
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
